// This file is auto-generated by @hey-api/openapi-ts

export const internal_httpapi_AcceptInviteRequestSchema = {
  properties: {
    password: {
      type: 'string'
    },
    token: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_AddLibraryRootRequestSchema = {
  properties: {
    relPath: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_AdminUserResponseSchema = {
  properties: {
    user: {
      $ref: '#/components/schemas/sudoStream_internal_auth.AdminUser'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_AuthTokensResponseSchema = {
  properties: {
    accessToken: {
      type: 'string'
    },
    backupCodes: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    user: {
      $ref: '#/components/schemas/sudoStream_internal_auth.PublicUser'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ChangeEmailRequestSchema = {
  properties: {
    newEmail: {
      type: 'string'
    },
    password: {
      type: 'string'
    },
    totp: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ChangePasswordRequestSchema = {
  properties: {
    currentPassword: {
      type: 'string'
    },
    newPassword: {
      type: 'string'
    },
    totp: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_CreateInviteRequestSchema = {
  properties: {
    email: {
      type: 'string'
    },
    expiresInHours: {
      type: 'integer'
    },
    role: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_CreateLibraryRequestSchema = {
  properties: {
    name: {
      type: 'string'
    },
    slug: {
      type: 'string'
    },
    type: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_CreateUserRequestSchema = {
  properties: {
    email: {
      type: 'string'
    },
    password: {
      type: 'string'
    },
    role: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_DisableTwoFactorRequestSchema = {
  properties: {
    code: {
      type: 'string'
    },
    password: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ErrorResponseSchema = {
  properties: {
    error: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_FavoritePatchRequestSchema = {
  properties: {
    favorited: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_FavoriteResponseSchema = {
  properties: {
    favorited: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_FolderTreeEntrySchema = {
  properties: {
    assignedLibraryId: {
      type: 'string'
    },
    name: {
      type: 'string'
    },
    relPath: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_FolderTreeResponseSchema = {
  properties: {
    entries: {
      items: {
        $ref: '#/components/schemas/internal_httpapi.FolderTreeEntry'
      },
      type: 'array',
      uniqueItems: false
    },
    path: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ForgotPasswordRequestSchema = {
  properties: {
    email: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_GrantsResponseSchema = {
  properties: {
    grants: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_access.UserGrantView'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_HealthResponseSchema = {
  properties: {
    status: {
      type: 'string'
    },
    version: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_HomeItemsResponseSchema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_homeshelf.ShelfItem'
      },
      type: 'array',
      uniqueItems: false
    },
    limit: {
      type: 'integer'
    },
    offset: {
      type: 'integer'
    },
    total: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_HomeStatsResponseSchema = {
  properties: {
    libraries: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_homeshelf.LibraryStat'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_InvitesResponseSchema = {
  properties: {
    invites: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_auth.InviteView'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_LibrariesResponseSchema = {
  properties: {
    libraries: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_access.Library'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_LibraryResponseSchema = {
  properties: {
    library: {
      $ref: '#/components/schemas/sudoStream_internal_access.Library'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_LoginRequestSchema = {
  properties: {
    email: {
      example: 'admin@localhost.lan',
      type: 'string'
    },
    password: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_LoginResponseSchema = {
  properties: {
    accessToken: {
      type: 'string'
    },
    pendingToken: {
      type: 'string'
    },
    status: {
      type: 'string'
    },
    user: {
      $ref: '#/components/schemas/sudoStream_internal_auth.PublicUser'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_MaintenanceRunResponseSchema = {
  properties: {
    run: {
      $ref: '#/components/schemas/sudoStream_internal_maintenance.Run'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_MaintenanceRunsResponseSchema = {
  properties: {
    runs: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_maintenance.Run'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_MaintenanceStatusResponseSchema = {
  properties: {
    actions: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_maintenance.ActionStatus'
      },
      type: 'array',
      uniqueItems: false
    },
    cacheBytes: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_MeResponseSchema = {
  properties: {
    user: {
      $ref: '#/components/schemas/sudoStream_internal_auth.PublicUser'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_OAuthErrorResponseSchema = {
  properties: {
    error: {
      type: 'string'
    },
    error_description: {
      type: 'string'
    },
    pending_token: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_OAuthTokenResponseSchema = {
  properties: {
    access_token: {
      type: 'string'
    },
    expires_in: {
      type: 'integer'
    },
    refresh_token: {
      type: 'string'
    },
    token_type: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_PatchLibraryRequestSchema = {
  properties: {
    name: {
      type: 'string'
    },
    type: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_PatchMaintenanceRequestSchema = {
  properties: {
    schedules: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_maintenance.ScheduleInput'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_PatchProviderSettingsRequestSchema = {
  properties: {
    allowOverrideUserMetadata: {
      type: 'boolean'
    },
    metadataApplyMode: {
      type: 'string'
    },
    metadataProvider: {
      type: 'string'
    },
    metadataWriteTarget: {
      type: 'string'
    },
    posterProvider: {
      type: 'string'
    },
    subtitleLanguages: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    subtitleProvider: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_PlaybackNegotiateRequestSchema = {
  properties: {
    deviceProfile: {
      $ref: '#/components/schemas/sudoStream_internal_playback.DeviceProfile'
    },
    fallback: {
      type: 'boolean'
    },
    qualityHeight: {
      description: 'QualityHeight is the selected ladder rung; 0 / omitted means original/source.',
      type: 'integer'
    },
    transcode: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_PlaybackResponseSchema = {
  properties: {
    audioTracks: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_transcode.TrackInfo'
      },
      type: 'array',
      uniqueItems: false
    },
    chapters: {
      description: 'Chapters are container chapter atoms on any video file (not limited to film/series).',
      items: {
        $ref: '#/components/schemas/sudoStream_internal_transcode.ChapterInfo'
      },
      type: 'array',
      uniqueItems: false
    },
    durationSeconds: {
      type: 'number'
    },
    encoder: {
      type: 'string'
    },
    error: {
      type: 'string'
    },
    masterUrl: {
      type: 'string'
    },
    packagingMode: {
      $ref: '#/components/schemas/sudoStream_internal_transcode.PackagingMode'
    },
    playMethod: {
      $ref: '#/components/schemas/sudoStream_internal_playback.PlayMethod'
    },
    providerSubtitleTracks: {
      items: {
        $ref: '#/components/schemas/internal_httpapi.ProviderSubtitleTrack'
      },
      type: 'array',
      uniqueItems: false
    },
    qualities: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_transcode.QualityInfo'
      },
      type: 'array',
      uniqueItems: false
    },
    series: {
      $ref: '#/components/schemas/internal_httpapi.PlaybackSeriesContext',
      description: 'Series is set only for paths in a series library with resolvable S/E identity.'
    },
    skipIntro: {
      $ref: '#/components/schemas/sudoStream_internal_skipsegment.Intro',
      description: 'SkipIntro is set when chapter metadata identifies an opening intro segment (E-23).'
    },
    status: {
      $ref: '#/components/schemas/sudoStream_internal_transcode.Status'
    },
    streamUrl: {
      type: 'string'
    },
    subtitleTracks: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_transcode.TrackInfo'
      },
      type: 'array',
      uniqueItems: false
    },
    toneMapped: {
      type: 'boolean'
    },
    userSubtitle: {
      $ref: '#/components/schemas/internal_httpapi.UserSubtitleTrack',
      description: 'UserSubtitle is the current user\'s uploaded caption when present (TTL 1d).'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_PlaybackSeriesContextSchema = {
  properties: {
    episode: {
      type: 'integer'
    },
    librarySlug: {
      type: 'string'
    },
    season: {
      type: 'integer'
    },
    showKey: {
      type: 'string'
    },
    showName: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ProviderAvailabilitySchema = {
  properties: {
    metadata: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    poster: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    subtitle: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ProviderSettingsResponseSchema = {
  properties: {
    available: {
      $ref: '#/components/schemas/internal_httpapi.ProviderAvailability'
    },
    settings: {
      $ref: '#/components/schemas/sudoStream_internal_provider.Settings'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ProviderSubtitleTrackSchema = {
  properties: {
    label: {
      type: 'string'
    },
    lang: {
      type: 'string'
    },
    url: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_PutGrantsRequestSchema = {
  properties: {
    grants: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_access.GrantInput'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_RefreshResponseSchema = {
  properties: {
    accessToken: {
      type: 'string'
    },
    user: {
      $ref: '#/components/schemas/sudoStream_internal_auth.PublicUser'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ResendInviteRequestSchema = {
  properties: {
    expiresInHours: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_ResetPasswordRequestSchema = {
  properties: {
    password: {
      type: 'string'
    },
    token: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_SearchResponseSchema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_metadata.SearchHit'
      },
      type: 'array',
      uniqueItems: false
    },
    limit: {
      type: 'integer'
    },
    offset: {
      type: 'integer'
    },
    total: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_SessionsResponseSchema = {
  properties: {
    sessions: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_auth.SessionView'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_StatusResponseSchema = {
  properties: {
    status: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_TrashListResponseSchema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_trash.Item'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_TrashSettingsResponseSchema = {
  properties: {
    retentionDays: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_TwoFactorConfirmRequestSchema = {
  properties: {
    code: {
      type: 'string'
    },
    pendingToken: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_TwoFactorSetupRequestSchema = {
  properties: {
    pendingToken: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_UpdateUserRequestSchema = {
  properties: {
    email: {
      type: 'string'
    },
    enabled: {
      type: 'boolean'
    },
    role: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_UserResponseSchema = {
  properties: {
    user: {
      $ref: '#/components/schemas/sudoStream_internal_auth.PublicUser'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_UserSubtitleTrackSchema = {
  properties: {
    label: {
      type: 'string'
    },
    lang: {
      type: 'string'
    },
    url: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_UsersResponseSchema = {
  properties: {
    users: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_auth.AdminUser'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_VerifyTwoFactorRequestSchema = {
  properties: {
    code: {
      type: 'string'
    },
    pendingToken: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_WatchPatchRequestSchema = {
  properties: {
    durationSeconds: {
      type: 'number'
    },
    positionSeconds: {
      type: 'number'
    },
    watched: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const internal_httpapi_WatchResponseSchema = {
  properties: {
    durationSeconds: {
      type: 'number'
    },
    positionSeconds: {
      type: 'number'
    },
    watched: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_access_GrantInputSchema = {
  properties: {
    libraryId: {
      type: 'string'
    },
    permissions: {
      $ref: '#/components/schemas/sudoStream_internal_access.LibraryPermissions'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_access_LibrarySchema = {
  properties: {
    id: {
      type: 'string'
    },
    name: {
      type: 'string'
    },
    relPath: {
      type: 'string'
    },
    roots: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    slug: {
      type: 'string'
    },
    type: {
      $ref: '#/components/schemas/sudoStream_internal_access.LibraryType'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_access_LibraryPermissionsSchema = {
  properties: {
    create: {
      type: 'boolean'
    },
    delete: {
      type: 'boolean'
    },
    read: {
      type: 'boolean'
    },
    update: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_access_LibraryTypeSchema = {
  enum: [
    'film',
    'series',
    'music',
    'photos',
    'other'
  ],
  type: 'string',
  'x-enum-varnames': [
    'LibraryTypeFilm',
    'LibraryTypeSeries',
    'LibraryTypeMusic',
    'LibraryTypePhotos',
    'LibraryTypeOther'
  ]
} as const;

export const sudoStream_internal_access_UserGrantViewSchema = {
  properties: {
    library: {
      $ref: '#/components/schemas/sudoStream_internal_access.Library'
    },
    permissions: {
      $ref: '#/components/schemas/sudoStream_internal_access.LibraryPermissions'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_auth_AdminUserSchema = {
  properties: {
    createdAt: {
      type: 'string'
    },
    email: {
      type: 'string'
    },
    emailVerified: {
      type: 'boolean'
    },
    enabled: {
      type: 'boolean'
    },
    has2FA: {
      type: 'boolean'
    },
    id: {
      type: 'string'
    },
    lastLoginAt: {
      type: 'string'
    },
    mustChangePassword: {
      type: 'boolean'
    },
    role: {
      type: 'string'
    },
    status: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_auth_InviteViewSchema = {
  properties: {
    createdAt: {
      type: 'string'
    },
    email: {
      type: 'string'
    },
    expired: {
      type: 'boolean'
    },
    expiresAt: {
      type: 'string'
    },
    id: {
      type: 'string'
    },
    role: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_auth_PublicUserSchema = {
  properties: {
    email: {
      type: 'string'
    },
    has2FA: {
      type: 'boolean'
    },
    id: {
      type: 'string'
    },
    mustChangePassword: {
      type: 'boolean'
    },
    role: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_auth_SessionViewSchema = {
  properties: {
    createdAt: {
      type: 'string'
    },
    current: {
      type: 'boolean'
    },
    expiresAt: {
      type: 'string'
    },
    id: {
      type: 'string'
    },
    ip: {
      type: 'string'
    },
    userAgent: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_auth_SettingsSchema = {
  properties: {
    emailConfirmationRequired: {
      type: 'boolean'
    },
    twoFactorRequired: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_auth_TwoFactorConfirmResultSchema = {
  properties: {
    backupCodes: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_auth_TwoFactorSetupSchema = {
  properties: {
    otpauthURL: {
      type: 'string'
    },
    secret: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_catalog_EpisodeSchema = {
  properties: {
    actions: {
      $ref: '#/components/schemas/sudoStream_internal_mediafs.Action'
    },
    episode: {
      type: 'integer'
    },
    episodeTitle: {
      type: 'string'
    },
    favorited: {
      type: 'boolean'
    },
    path: {
      type: 'string'
    },
    posterUrl: {
      type: 'string'
    },
    season: {
      type: 'integer'
    },
    title: {
      type: 'string'
    },
    watched: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_catalog_LibraryCatalogSchema = {
  properties: {
    limit: {
      type: 'integer'
    },
    movies: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_catalog.Movie'
      },
      type: 'array',
      uniqueItems: false
    },
    offset: {
      type: 'integer'
    },
    shows: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_catalog.ShowSummary'
      },
      type: 'array',
      uniqueItems: false
    },
    total: {
      type: 'integer'
    },
    type: {
      $ref: '#/components/schemas/sudoStream_internal_access.LibraryType'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_catalog_MovieSchema = {
  properties: {
    actions: {
      $ref: '#/components/schemas/sudoStream_internal_mediafs.Action'
    },
    favorited: {
      type: 'boolean'
    },
    path: {
      type: 'string'
    },
    posterUrl: {
      type: 'string'
    },
    title: {
      type: 'string'
    },
    watched: {
      type: 'boolean'
    },
    year: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_catalog_SeasonEpisodesSchema = {
  properties: {
    episodes: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_catalog.Episode'
      },
      type: 'array',
      uniqueItems: false
    },
    limit: {
      type: 'integer'
    },
    offset: {
      type: 'integer'
    },
    season: {
      type: 'integer'
    },
    total: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_catalog_SeasonSummarySchema = {
  properties: {
    episodeCount: {
      type: 'integer'
    },
    season: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_catalog_ShowDetailSchema = {
  properties: {
    actions: {
      $ref: '#/components/schemas/sudoStream_internal_mediafs.Action'
    },
    episodeCount: {
      type: 'integer'
    },
    name: {
      type: 'string'
    },
    posterPath: {
      type: 'string'
    },
    posterUrl: {
      type: 'string'
    },
    seasonCount: {
      type: 'integer'
    },
    seasons: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_catalog.SeasonSummary'
      },
      type: 'array',
      uniqueItems: false
    },
    showKey: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_catalog_ShowSummarySchema = {
  properties: {
    actions: {
      $ref: '#/components/schemas/sudoStream_internal_mediafs.Action'
    },
    episodeCount: {
      type: 'integer'
    },
    name: {
      type: 'string'
    },
    posterPath: {
      type: 'string'
    },
    posterUrl: {
      type: 'string'
    },
    seasonCount: {
      type: 'integer'
    },
    showKey: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_dlna_SettingsSchema = {
  properties: {
    enabled: {
      type: 'boolean'
    },
    udn: {
      description: 'UDN is a stable uuid:… for SSDP (generated on first save when empty).',
      type: 'string'
    },
    userId: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_homeshelf_LibraryStatSchema = {
  properties: {
    libraryId: {
      type: 'string'
    },
    name: {
      type: 'string'
    },
    slug: {
      type: 'string'
    },
    totalCount: {
      type: 'integer'
    },
    watchedCount: {
      type: 'integer'
    },
    watchedPercent: {
      type: 'number'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_homeshelf_ShelfItemSchema = {
  properties: {
    durationSeconds: {
      type: 'number'
    },
    librarySlug: {
      type: 'string'
    },
    path: {
      type: 'string'
    },
    positionSeconds: {
      type: 'number'
    },
    posterUrl: {
      type: 'string'
    },
    title: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_maintenance_ActionStatusSchema = {
  properties: {
    action: {
      type: 'string'
    },
    latestRun: {
      $ref: '#/components/schemas/sudoStream_internal_maintenance.Run'
    },
    running: {
      type: 'boolean'
    },
    schedule: {
      $ref: '#/components/schemas/sudoStream_internal_maintenance.Schedule'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_maintenance_RunSchema = {
  properties: {
    action: {
      type: 'string'
    },
    finishedAt: {
      type: 'string'
    },
    id: {
      type: 'string'
    },
    libraryId: {
      type: 'string'
    },
    startedAt: {
      type: 'string'
    },
    status: {
      type: 'string'
    },
    summary: {
      additionalProperties: {},
      type: 'object'
    },
    trigger: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_maintenance_ScheduleSchema = {
  properties: {
    action: {
      type: 'string'
    },
    config: {
      additionalProperties: {},
      type: 'object'
    },
    cron: {
      type: 'string'
    },
    enabled: {
      type: 'boolean'
    },
    id: {
      type: 'string'
    },
    libraryId: {
      type: 'string'
    },
    updatedAt: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_maintenance_ScheduleInputSchema = {
  properties: {
    action: {
      type: 'string'
    },
    config: {
      additionalProperties: {},
      type: 'object'
    },
    cron: {
      type: 'string'
    },
    enabled: {
      type: 'boolean'
    },
    libraryId: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_mediafs_ActionSchema = {
  properties: {
    canDelete: {
      type: 'boolean'
    },
    download: {
      type: 'string'
    },
    play: {
      type: 'string'
    },
    thumbnail: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_mediafs_BreadcrumbSchema = {
  properties: {
    name: {
      type: 'string'
    },
    path: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_mediafs_BrowseResponseSchema = {
  properties: {
    breadcrumbs: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_mediafs.Breadcrumb'
      },
      type: 'array',
      uniqueItems: false
    },
    folder: {
      $ref: '#/components/schemas/sudoStream_internal_mediafs.Item'
    },
    limit: {
      type: 'integer'
    },
    offset: {
      type: 'integer'
    },
    path: {
      type: 'string'
    },
    total: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_mediafs_ItemSchema = {
  properties: {
    actions: {
      $ref: '#/components/schemas/sudoStream_internal_mediafs.Action'
    },
    children: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_mediafs.Item'
      },
      type: 'array',
      uniqueItems: false
    },
    extension: {
      type: 'string'
    },
    favorited: {
      type: 'boolean'
    },
    isDir: {
      type: 'boolean'
    },
    mimeType: {
      type: 'string'
    },
    name: {
      type: 'string'
    },
    path: {
      type: 'string'
    },
    size: {
      type: 'integer'
    },
    watched: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_metadata_FilenameHintSchema = {
  properties: {
    episode: {
      type: 'integer'
    },
    season: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_metadata_MetadataResponseSchema = {
  properties: {
    display_name: {
      type: 'string'
    },
    effective: {
      $ref: '#/components/schemas/sudoStream_internal_metadata.VideoFields'
    },
    filename_hint: {
      $ref: '#/components/schemas/sudoStream_internal_metadata.FilenameHint'
    },
    library_type: {
      $ref: '#/components/schemas/sudoStream_internal_access.LibraryType'
    },
    overridden_by: {
      type: 'string'
    },
    path: {
      type: 'string'
    },
    probed_at: {
      type: 'string'
    },
    source: {
      $ref: '#/components/schemas/sudoStream_internal_metadata.SourceFields'
    },
    uses_metadata_for_display: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_metadata_PatchRequestSchema = {
  properties: {
    fields: {
      additionalProperties: {
        $ref: '#/components/schemas/sudoStream_internal_metadata.jsonValue'
      },
      type: 'object'
    },
    target: {
      $ref: '#/components/schemas/sudoStream_internal_metadata.PatchTarget'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_metadata_PatchTargetSchema = {
  enum: [
    'override',
    'file'
  ],
  type: 'string',
  'x-enum-varnames': [
    'PatchTargetOverride',
    'PatchTargetFile'
  ]
} as const;

export const sudoStream_internal_metadata_SearchHitSchema = {
  properties: {
    librarySlug: {
      type: 'string'
    },
    libraryType: {
      $ref: '#/components/schemas/sudoStream_internal_access.LibraryType'
    },
    path: {
      type: 'string'
    },
    showKey: {
      type: 'string'
    },
    title: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_metadata_SourceFieldsSchema = {
  properties: {
    original: {
      $ref: '#/components/schemas/sudoStream_internal_metadata.VideoFields'
    },
    override: {
      $ref: '#/components/schemas/sudoStream_internal_metadata.VideoFields'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_metadata_VideoFieldsSchema = {
  properties: {
    actors: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    audio_channels: {
      type: 'integer'
    },
    audio_codec: {
      type: 'string'
    },
    audio_languages: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    bitrate: {
      type: 'integer'
    },
    composer: {
      type: 'string'
    },
    content_rating: {
      type: 'string'
    },
    country: {
      type: 'string'
    },
    description: {
      type: 'string'
    },
    directors: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    duration_seconds: {
      type: 'number'
    },
    ed2k_hash: {
      type: 'string'
    },
    episode: {
      type: 'integer'
    },
    episode_title: {
      type: 'string'
    },
    frame_rate: {
      type: 'string'
    },
    genres: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    hash_file_size: {
      description: 'size when hashes were computed',
      type: 'integer'
    },
    height: {
      type: 'integer'
    },
    imdb_id: {
      type: 'string'
    },
    language: {
      type: 'string'
    },
    movie_hash: {
      description: 'System-owned identity hashes (scan-time; never overwritten; not PATCH-editable).',
      type: 'string'
    },
    original_title: {
      type: 'string'
    },
    producers: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    release_date: {
      type: 'string'
    },
    season: {
      type: 'integer'
    },
    show: {
      type: 'string'
    },
    sort_title: {
      type: 'string'
    },
    studio: {
      type: 'string'
    },
    tags: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    title: {
      type: 'string'
    },
    tmdb_id: {
      type: 'string'
    },
    tvdb_id: {
      type: 'string'
    },
    tvmaze_id: {
      type: 'string'
    },
    video_codec: {
      type: 'string'
    },
    width: {
      type: 'integer'
    },
    writers: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    year: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_metadata_jsonValueSchema = {
  type: 'object'
} as const;

export const sudoStream_internal_network_ProbeResultSchema = {
  properties: {
    durationMs: {
      type: 'integer'
    },
    error: {
      type: 'string'
    },
    ok: {
      type: 'boolean'
    },
    statusCode: {
      type: 'integer'
    },
    via: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_network_SettingsSchema = {
  properties: {
    hasProxyPassword: {
      type: 'boolean'
    },
    noProxy: {
      type: 'string'
    },
    proxyPassword: {
      type: 'string'
    },
    proxyUrl: {
      type: 'string'
    },
    proxyUser: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_playback_DeviceProfileSchema = {
  properties: {
    directPlay: {
      items: {
        $ref: '#/components/schemas/sudoStream_internal_playback.DirectPlayProfile'
      },
      type: 'array',
      uniqueItems: false
    },
    maxStaticBitrate: {
      type: 'integer'
    },
    preferHls: {
      type: 'boolean'
    },
    subtitle: {
      description: 'Subtitle lists supported subtitle delivery modes (e.g. "external").',
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_playback_DirectPlayProfileSchema = {
  properties: {
    audioCodec: {
      type: 'string'
    },
    container: {
      type: 'string'
    },
    videoCodec: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_playback_PlayMethodSchema = {
  enum: [
    'directPlay',
    'remux',
    'transcode'
  ],
  type: 'string',
  'x-enum-varnames': [
    'MethodDirectPlay',
    'MethodRemux',
    'MethodTranscode'
  ]
} as const;

export const sudoStream_internal_provider_SettingsSchema = {
  properties: {
    allowOverrideUserMetadata: {
      type: 'boolean'
    },
    libraryId: {
      type: 'string'
    },
    metadataApplyMode: {
      type: 'string'
    },
    metadataProvider: {
      type: 'string'
    },
    metadataWriteTarget: {
      type: 'string'
    },
    posterProvider: {
      type: 'string'
    },
    subtitleLanguages: {
      items: {
        type: 'string'
      },
      type: 'array',
      uniqueItems: false
    },
    subtitleProvider: {
      type: 'string'
    },
    updatedAt: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_skipsegment_IntroSchema = {
  properties: {
    endMs: {
      type: 'integer'
    },
    source: {
      type: 'string'
    },
    startMs: {
      type: 'integer'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_transcode_ChapterInfoSchema = {
  properties: {
    endSeconds: {
      type: 'number'
    },
    startSeconds: {
      type: 'number'
    },
    title: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_transcode_DownmixAlgorithmSchema = {
  enum: [
    'none',
    'ac4'
  ],
  type: 'string',
  'x-enum-varnames': [
    'DownmixNone',
    'DownmixAC4'
  ]
} as const;

export const sudoStream_internal_transcode_HwAccelSchema = {
  enum: [
    'off',
    'qsv',
    'vaapi',
    'nvenc',
    'rockchip'
  ],
  type: 'string',
  'x-enum-varnames': [
    'HwAccelOff',
    'HwAccelQSV',
    'HwAccelVAAPI',
    'HwAccelNVENC',
    'HwAccelRockchip'
  ]
} as const;

export const sudoStream_internal_transcode_PackagingModeSchema = {
  enum: [
    'remux',
    'transcode'
  ],
  type: 'string',
  'x-enum-varnames': [
    'PackagingRemux',
    'PackagingTranscode'
  ]
} as const;

export const sudoStream_internal_transcode_QualityInfoSchema = {
  properties: {
    height: {
      type: 'integer'
    },
    label: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_transcode_StatusSchema = {
  enum: [
    'idle',
    'ready',
    'processing',
    'error'
  ],
  type: 'string',
  'x-enum-varnames': [
    'StatusIdle',
    'StatusReady',
    'StatusProcessing',
    'StatusError'
  ]
} as const;

export const sudoStream_internal_transcode_ToneMappingAlgorithmSchema = {
  enum: [
    'bt2390',
    'hable',
    'reinhard',
    'mobius'
  ],
  type: 'string',
  'x-enum-varnames': [
    'ToneMappingBT2390',
    'ToneMappingHable',
    'ToneMappingReinhard',
    'ToneMappingMobius'
  ]
} as const;

export const sudoStream_internal_transcode_TrackInfoSchema = {
  properties: {
    id: {
      type: 'string'
    },
    label: {
      type: 'string'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_transcode_TranscodeSettingsSchema = {
  properties: {
    downmixAlgorithm: {
      $ref: '#/components/schemas/sudoStream_internal_transcode.DownmixAlgorithm'
    },
    hwAccel: {
      $ref: '#/components/schemas/sudoStream_internal_transcode.HwAccel'
    },
    toneMappingAlgorithm: {
      $ref: '#/components/schemas/sudoStream_internal_transcode.ToneMappingAlgorithm'
    },
    toneMappingEnabled: {
      type: 'boolean'
    }
  },
  type: 'object'
} as const;

export const sudoStream_internal_trash_ItemSchema = {
  properties: {
    deletedAt: {
      type: 'string'
    },
    deletedBy: {
      type: 'string'
    },
    id: {
      type: 'string'
    },
    libraryId: {
      type: 'string'
    },
    originalRelPath: {
      type: 'string'
    },
    trashRelPath: {
      type: 'string'
    }
  },
  type: 'object'
} as const;
