// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8080' | (string & {});
};

export type InternalHttpapiAcceptInviteRequest = {
  password?: string;
  token?: string;
};

export type InternalHttpapiAddLibraryRootRequest = {
  relPath?: string;
};

export type InternalHttpapiAdminUserResponse = {
  user?: SudoStreamInternalAuthAdminUser;
};

export type InternalHttpapiAuthTokensResponse = {
  accessToken?: string;
  backupCodes?: Array<string>;
  user?: SudoStreamInternalAuthPublicUser;
};

export type InternalHttpapiChangeEmailRequest = {
  newEmail?: string;
  password?: string;
  totp?: string;
};

export type InternalHttpapiChangePasswordRequest = {
  currentPassword?: string;
  newPassword?: string;
  totp?: string;
};

export type InternalHttpapiCreateInviteRequest = {
  email?: string;
  expiresInHours?: number;
  role?: string;
};

export type InternalHttpapiCreateLibraryRequest = {
  name?: string;
  slug?: string;
  type?: string;
};

export type InternalHttpapiCreateUserRequest = {
  email?: string;
  password?: string;
  role?: string;
};

export type InternalHttpapiDisableTwoFactorRequest = {
  code?: string;
  password?: string;
};

export type InternalHttpapiErrorResponse = {
  error?: string;
};

export type InternalHttpapiFavoritePatchRequest = {
  favorited?: boolean;
};

export type InternalHttpapiFavoriteResponse = {
  favorited?: boolean;
};

export type InternalHttpapiFolderTreeEntry = {
  assignedLibraryId?: string;
  name?: string;
  relPath?: string;
};

export type InternalHttpapiFolderTreeResponse = {
  entries?: Array<InternalHttpapiFolderTreeEntry>;
  path?: string;
};

export type InternalHttpapiForgotPasswordRequest = {
  email?: string;
};

export type InternalHttpapiGrantsResponse = {
  grants?: Array<SudoStreamInternalAccessUserGrantView>;
};

export type InternalHttpapiHealthResponse = {
  status?: string;
  version?: string;
};

export type InternalHttpapiHomeItemsResponse = {
  items?: Array<SudoStreamInternalHomeshelfShelfItem>;
  limit?: number;
  offset?: number;
  total?: number;
};

export type InternalHttpapiHomeStatsResponse = {
  libraries?: Array<SudoStreamInternalHomeshelfLibraryStat>;
};

export type InternalHttpapiInvitesResponse = {
  invites?: Array<SudoStreamInternalAuthInviteView>;
};

export type InternalHttpapiLibrariesResponse = {
  libraries?: Array<SudoStreamInternalAccessLibrary>;
};

export type InternalHttpapiLibraryResponse = {
  library?: SudoStreamInternalAccessLibrary;
};

export type InternalHttpapiLoginRequest = {
  email?: string;
  password?: string;
};

export type InternalHttpapiLoginResponse = {
  accessToken?: string;
  pendingToken?: string;
  status?: string;
  user?: SudoStreamInternalAuthPublicUser;
};

export type InternalHttpapiMaintenanceRunResponse = {
  run?: SudoStreamInternalMaintenanceRun;
};

export type InternalHttpapiMaintenanceRunsResponse = {
  runs?: Array<SudoStreamInternalMaintenanceRun>;
};

export type InternalHttpapiMaintenanceStatusResponse = {
  actions?: Array<SudoStreamInternalMaintenanceActionStatus>;
  cacheBytes?: number;
};

export type InternalHttpapiMeResponse = {
  user?: SudoStreamInternalAuthPublicUser;
};

export type InternalHttpapiOAuthErrorResponse = {
  error?: string;
  error_description?: string;
  pending_token?: string;
};

export type InternalHttpapiOAuthTokenResponse = {
  access_token?: string;
  expires_in?: number;
  refresh_token?: string;
  token_type?: string;
};

export type InternalHttpapiPatchLibraryRequest = {
  name?: string;
  type?: string;
};

export type InternalHttpapiPatchMaintenanceRequest = {
  schedules?: Array<SudoStreamInternalMaintenanceScheduleInput>;
};

export type InternalHttpapiPatchProviderSettingsRequest = {
  allowOverrideUserMetadata?: boolean;
  metadataApplyMode?: string;
  metadataProvider?: string;
  metadataWriteTarget?: string;
  posterProvider?: string;
  subtitleLanguages?: Array<string>;
  subtitleProvider?: string;
};

export type InternalHttpapiPlaybackNegotiateRequest = {
  deviceProfile?: SudoStreamInternalPlaybackDeviceProfile;
  fallback?: boolean;
  /**
   * QualityHeight is the selected ladder rung; 0 / omitted means original/source.
   */
  qualityHeight?: number;
  transcode?: boolean;
};

export type InternalHttpapiPlaybackResponse = {
  audioTracks?: Array<SudoStreamInternalTranscodeTrackInfo>;
  /**
   * Chapters are container chapter atoms on any video file (not limited to film/series).
   */
  chapters?: Array<SudoStreamInternalTranscodeChapterInfo>;
  durationSeconds?: number;
  encoder?: string;
  error?: string;
  masterUrl?: string;
  packagingMode?: SudoStreamInternalTranscodePackagingMode;
  playMethod?: SudoStreamInternalPlaybackPlayMethod;
  providerSubtitleTracks?: Array<InternalHttpapiProviderSubtitleTrack>;
  qualities?: Array<SudoStreamInternalTranscodeQualityInfo>;
  /**
   * Series is set only for paths in a series library with resolvable S/E identity.
   */
  series?: InternalHttpapiPlaybackSeriesContext;
  status?: SudoStreamInternalTranscodeStatus;
  streamUrl?: string;
  subtitleTracks?: Array<SudoStreamInternalTranscodeTrackInfo>;
  toneMapped?: boolean;
  /**
   * UserSubtitle is the current user's uploaded caption when present (TTL 1d).
   */
  userSubtitle?: InternalHttpapiUserSubtitleTrack;
};

export type InternalHttpapiPlaybackSeriesContext = {
  episode?: number;
  librarySlug?: string;
  season?: number;
  showKey?: string;
  showName?: string;
};

export type InternalHttpapiProviderAvailability = {
  metadata?: Array<string>;
  poster?: Array<string>;
  subtitle?: Array<string>;
};

export type InternalHttpapiProviderSettingsResponse = {
  available?: InternalHttpapiProviderAvailability;
  settings?: SudoStreamInternalProviderSettings;
};

export type InternalHttpapiProviderSubtitleTrack = {
  label?: string;
  lang?: string;
  url?: string;
};

export type InternalHttpapiPutGrantsRequest = {
  grants?: Array<SudoStreamInternalAccessGrantInput>;
};

export type InternalHttpapiRefreshResponse = {
  accessToken?: string;
  user?: SudoStreamInternalAuthPublicUser;
};

export type InternalHttpapiResendInviteRequest = {
  expiresInHours?: number;
};

export type InternalHttpapiResetPasswordRequest = {
  password?: string;
  token?: string;
};

export type InternalHttpapiSearchResponse = {
  items?: Array<SudoStreamInternalMetadataSearchHit>;
  limit?: number;
  offset?: number;
  total?: number;
};

export type InternalHttpapiSessionsResponse = {
  sessions?: Array<SudoStreamInternalAuthSessionView>;
};

export type InternalHttpapiStatusResponse = {
  status?: string;
};

export type InternalHttpapiTrashListResponse = {
  items?: Array<SudoStreamInternalTrashItem>;
};

export type InternalHttpapiTrashSettingsResponse = {
  retentionDays?: number;
};

export type InternalHttpapiTwoFactorConfirmRequest = {
  code?: string;
  pendingToken?: string;
};

export type InternalHttpapiTwoFactorSetupRequest = {
  pendingToken?: string;
};

export type InternalHttpapiUpdateUserRequest = {
  email?: string;
  enabled?: boolean;
  role?: string;
};

export type InternalHttpapiUserResponse = {
  user?: SudoStreamInternalAuthPublicUser;
};

export type InternalHttpapiUserSubtitleTrack = {
  label?: string;
  lang?: string;
  url?: string;
};

export type InternalHttpapiUsersResponse = {
  users?: Array<SudoStreamInternalAuthAdminUser>;
};

export type InternalHttpapiVerifyTwoFactorRequest = {
  code?: string;
  pendingToken?: string;
};

export type InternalHttpapiWatchPatchRequest = {
  durationSeconds?: number;
  positionSeconds?: number;
  watched?: boolean;
};

export type InternalHttpapiWatchResponse = {
  durationSeconds?: number;
  positionSeconds?: number;
  watched?: boolean;
};

export type SudoStreamInternalAccessGrantInput = {
  libraryId?: string;
  permissions?: SudoStreamInternalAccessLibraryPermissions;
};

export type SudoStreamInternalAccessLibrary = {
  id?: string;
  name?: string;
  relPath?: string;
  roots?: Array<string>;
  slug?: string;
  type?: SudoStreamInternalAccessLibraryType;
};

export type SudoStreamInternalAccessLibraryPermissions = {
  create?: boolean;
  delete?: boolean;
  read?: boolean;
  update?: boolean;
};

export type SudoStreamInternalAccessLibraryType = 'film' | 'series' | 'music' | 'photos' | 'other';

export type SudoStreamInternalAccessUserGrantView = {
  library?: SudoStreamInternalAccessLibrary;
  permissions?: SudoStreamInternalAccessLibraryPermissions;
};

export type SudoStreamInternalAuthAdminUser = {
  createdAt?: string;
  email?: string;
  emailVerified?: boolean;
  enabled?: boolean;
  has2FA?: boolean;
  id?: string;
  lastLoginAt?: string;
  mustChangePassword?: boolean;
  role?: string;
  status?: string;
};

export type SudoStreamInternalAuthInviteView = {
  createdAt?: string;
  email?: string;
  expired?: boolean;
  expiresAt?: string;
  id?: string;
  role?: string;
};

export type SudoStreamInternalAuthPublicUser = {
  email?: string;
  has2FA?: boolean;
  id?: string;
  mustChangePassword?: boolean;
  role?: string;
};

export type SudoStreamInternalAuthSessionView = {
  createdAt?: string;
  current?: boolean;
  expiresAt?: string;
  id?: string;
  ip?: string;
  userAgent?: string;
};

export type SudoStreamInternalAuthSettings = {
  emailConfirmationRequired?: boolean;
  twoFactorRequired?: boolean;
};

export type SudoStreamInternalAuthTwoFactorConfirmResult = {
  backupCodes?: Array<string>;
};

export type SudoStreamInternalAuthTwoFactorSetup = {
  otpauthURL?: string;
  secret?: string;
};

export type SudoStreamInternalCatalogEpisode = {
  actions?: SudoStreamInternalMediafsAction;
  episode?: number;
  episodeTitle?: string;
  favorited?: boolean;
  path?: string;
  posterUrl?: string;
  season?: number;
  title?: string;
  watched?: boolean;
};

export type SudoStreamInternalCatalogLibraryCatalog = {
  limit?: number;
  movies?: Array<SudoStreamInternalCatalogMovie>;
  offset?: number;
  shows?: Array<SudoStreamInternalCatalogShowSummary>;
  total?: number;
  type?: SudoStreamInternalAccessLibraryType;
};

export type SudoStreamInternalCatalogMovie = {
  actions?: SudoStreamInternalMediafsAction;
  favorited?: boolean;
  path?: string;
  posterUrl?: string;
  title?: string;
  watched?: boolean;
  year?: number;
};

export type SudoStreamInternalCatalogSeasonEpisodes = {
  episodes?: Array<SudoStreamInternalCatalogEpisode>;
  limit?: number;
  offset?: number;
  season?: number;
  total?: number;
};

export type SudoStreamInternalCatalogSeasonSummary = {
  episodeCount?: number;
  season?: number;
};

export type SudoStreamInternalCatalogShowDetail = {
  actions?: SudoStreamInternalMediafsAction;
  episodeCount?: number;
  name?: string;
  posterPath?: string;
  posterUrl?: string;
  seasonCount?: number;
  seasons?: Array<SudoStreamInternalCatalogSeasonSummary>;
  showKey?: string;
};

export type SudoStreamInternalCatalogShowSummary = {
  actions?: SudoStreamInternalMediafsAction;
  episodeCount?: number;
  name?: string;
  posterPath?: string;
  posterUrl?: string;
  seasonCount?: number;
  showKey?: string;
};

export type SudoStreamInternalDlnaSettings = {
  enabled?: boolean;
  /**
   * UDN is a stable uuid:… for SSDP (generated on first save when empty).
   */
  udn?: string;
  userId?: string;
};

export type SudoStreamInternalHomeshelfLibraryStat = {
  libraryId?: string;
  name?: string;
  slug?: string;
  totalCount?: number;
  watchedCount?: number;
  watchedPercent?: number;
};

export type SudoStreamInternalHomeshelfShelfItem = {
  durationSeconds?: number;
  librarySlug?: string;
  path?: string;
  positionSeconds?: number;
  posterUrl?: string;
  title?: string;
};

export type SudoStreamInternalMaintenanceActionStatus = {
  action?: string;
  latestRun?: SudoStreamInternalMaintenanceRun;
  running?: boolean;
  schedule?: SudoStreamInternalMaintenanceSchedule;
};

export type SudoStreamInternalMaintenanceRun = {
  action?: string;
  finishedAt?: string;
  id?: string;
  libraryId?: string;
  startedAt?: string;
  status?: string;
  summary?: {
    [key: string]: unknown;
  };
  trigger?: string;
};

export type SudoStreamInternalMaintenanceSchedule = {
  action?: string;
  config?: {
    [key: string]: unknown;
  };
  cron?: string;
  enabled?: boolean;
  id?: string;
  libraryId?: string;
  updatedAt?: string;
};

export type SudoStreamInternalMaintenanceScheduleInput = {
  action?: string;
  config?: {
    [key: string]: unknown;
  };
  cron?: string;
  enabled?: boolean;
  libraryId?: string;
};

export type SudoStreamInternalMediafsAction = {
  canDelete?: boolean;
  download?: string;
  play?: string;
  thumbnail?: string;
};

export type SudoStreamInternalMediafsBreadcrumb = {
  name?: string;
  path?: string;
};

export type SudoStreamInternalMediafsBrowseResponse = {
  breadcrumbs?: Array<SudoStreamInternalMediafsBreadcrumb>;
  folder?: SudoStreamInternalMediafsItem;
  limit?: number;
  offset?: number;
  path?: string;
  total?: number;
};

export type SudoStreamInternalMediafsItem = {
  actions?: SudoStreamInternalMediafsAction;
  children?: Array<SudoStreamInternalMediafsItem>;
  extension?: string;
  favorited?: boolean;
  isDir?: boolean;
  mimeType?: string;
  name?: string;
  path?: string;
  size?: number;
  watched?: boolean;
};

export type SudoStreamInternalMetadataFilenameHint = {
  episode?: number;
  season?: number;
};

export type SudoStreamInternalMetadataMetadataResponse = {
  display_name?: string;
  effective?: SudoStreamInternalMetadataVideoFields;
  filename_hint?: SudoStreamInternalMetadataFilenameHint;
  library_type?: SudoStreamInternalAccessLibraryType;
  overridden_by?: string;
  path?: string;
  probed_at?: string;
  source?: SudoStreamInternalMetadataSourceFields;
  uses_metadata_for_display?: boolean;
};

export type SudoStreamInternalMetadataPatchRequest = {
  fields?: {
    [key: string]: SudoStreamInternalMetadataJsonValue;
  };
  target?: SudoStreamInternalMetadataPatchTarget;
};

export type SudoStreamInternalMetadataPatchTarget = 'override' | 'file';

export type SudoStreamInternalMetadataSearchHit = {
  librarySlug?: string;
  libraryType?: SudoStreamInternalAccessLibraryType;
  path?: string;
  showKey?: string;
  title?: string;
};

export type SudoStreamInternalMetadataSourceFields = {
  original?: SudoStreamInternalMetadataVideoFields;
  override?: SudoStreamInternalMetadataVideoFields;
};

export type SudoStreamInternalMetadataVideoFields = {
  actors?: Array<string>;
  audio_channels?: number;
  audio_codec?: string;
  audio_languages?: Array<string>;
  bitrate?: number;
  composer?: string;
  content_rating?: string;
  country?: string;
  description?: string;
  directors?: Array<string>;
  duration_seconds?: number;
  ed2k_hash?: string;
  episode?: number;
  episode_title?: string;
  frame_rate?: string;
  genres?: Array<string>;
  /**
   * size when hashes were computed
   */
  hash_file_size?: number;
  height?: number;
  imdb_id?: string;
  language?: string;
  /**
   * System-owned identity hashes (scan-time; never overwritten; not PATCH-editable).
   */
  movie_hash?: string;
  original_title?: string;
  producers?: Array<string>;
  release_date?: string;
  season?: number;
  show?: string;
  sort_title?: string;
  studio?: string;
  tags?: Array<string>;
  title?: string;
  tmdb_id?: string;
  tvdb_id?: string;
  tvmaze_id?: string;
  video_codec?: string;
  width?: number;
  writers?: Array<string>;
  year?: number;
};

export type SudoStreamInternalMetadataJsonValue = {
  [key: string]: unknown;
};

export type SudoStreamInternalNetworkProbeResult = {
  durationMs?: number;
  error?: string;
  ok?: boolean;
  statusCode?: number;
  via?: string;
};

export type SudoStreamInternalNetworkSettings = {
  hasProxyPassword?: boolean;
  noProxy?: string;
  proxyPassword?: string;
  proxyUrl?: string;
  proxyUser?: string;
};

export type SudoStreamInternalPlaybackDeviceProfile = {
  directPlay?: Array<SudoStreamInternalPlaybackDirectPlayProfile>;
  maxStaticBitrate?: number;
  preferHls?: boolean;
  /**
   * Subtitle lists supported subtitle delivery modes (e.g. "external").
   */
  subtitle?: Array<string>;
};

export type SudoStreamInternalPlaybackDirectPlayProfile = {
  audioCodec?: string;
  container?: string;
  videoCodec?: string;
};

export type SudoStreamInternalPlaybackPlayMethod = 'directPlay' | 'remux' | 'transcode';

export type SudoStreamInternalProviderSettings = {
  allowOverrideUserMetadata?: boolean;
  libraryId?: string;
  metadataApplyMode?: string;
  metadataProvider?: string;
  metadataWriteTarget?: string;
  posterProvider?: string;
  subtitleLanguages?: Array<string>;
  subtitleProvider?: string;
  updatedAt?: string;
};

export type SudoStreamInternalTranscodeChapterInfo = {
  endSeconds?: number;
  startSeconds?: number;
  title?: string;
};

export type SudoStreamInternalTranscodeDownmixAlgorithm = 'none' | 'ac4';

export type SudoStreamInternalTranscodeHwAccel = 'off' | 'qsv' | 'vaapi' | 'nvenc' | 'rockchip';

export type SudoStreamInternalTranscodePackagingMode = 'remux' | 'transcode';

export type SudoStreamInternalTranscodeQualityInfo = {
  height?: number;
  label?: string;
};

export type SudoStreamInternalTranscodeStatus = 'idle' | 'ready' | 'processing' | 'error';

export type SudoStreamInternalTranscodeToneMappingAlgorithm = 'bt2390' | 'hable' | 'reinhard' | 'mobius';

export type SudoStreamInternalTranscodeTrackInfo = {
  id?: string;
  label?: string;
};

export type SudoStreamInternalTranscodeTranscodeSettings = {
  downmixAlgorithm?: SudoStreamInternalTranscodeDownmixAlgorithm;
  hwAccel?: SudoStreamInternalTranscodeHwAccel;
  toneMappingAlgorithm?: SudoStreamInternalTranscodeToneMappingAlgorithm;
  toneMappingEnabled?: boolean;
};

export type SudoStreamInternalTrashItem = {
  deletedAt?: string;
  deletedBy?: string;
  id?: string;
  libraryId?: string;
  originalRelPath?: string;
  trashRelPath?: string;
};

export type GetApiAdminDlnaSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/dlna/settings';
};

export type GetApiAdminDlnaSettingsErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminDlnaSettingsError = GetApiAdminDlnaSettingsErrors[keyof GetApiAdminDlnaSettingsErrors];

export type GetApiAdminDlnaSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalDlnaSettings;
};

export type GetApiAdminDlnaSettingsResponse = GetApiAdminDlnaSettingsResponses[keyof GetApiAdminDlnaSettingsResponses];

export type PatchApiAdminDlnaSettingsData = {
  /**
   * DLNA settings
   */
  body: SudoStreamInternalDlnaSettings;
  path?: never;
  query?: never;
  url: '/api/admin/dlna/settings';
};

export type PatchApiAdminDlnaSettingsErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiAdminDlnaSettingsError = PatchApiAdminDlnaSettingsErrors[keyof PatchApiAdminDlnaSettingsErrors];

export type PatchApiAdminDlnaSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalDlnaSettings;
};

export type PatchApiAdminDlnaSettingsResponse = PatchApiAdminDlnaSettingsResponses[keyof PatchApiAdminDlnaSettingsResponses];

export type GetApiAdminFolderTreeData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parent path under media root
     */
    path?: string;
  };
  url: '/api/admin/folder-tree';
};

export type GetApiAdminFolderTreeErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminFolderTreeError = GetApiAdminFolderTreeErrors[keyof GetApiAdminFolderTreeErrors];

export type GetApiAdminFolderTreeResponses = {
  /**
   * OK
   */
  200: InternalHttpapiFolderTreeResponse;
};

export type GetApiAdminFolderTreeResponse = GetApiAdminFolderTreeResponses[keyof GetApiAdminFolderTreeResponses];

export type GetApiAdminInvitesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by email
     */
    email?: string;
  };
  url: '/api/admin/invites';
};

export type GetApiAdminInvitesErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminInvitesError = GetApiAdminInvitesErrors[keyof GetApiAdminInvitesErrors];

export type GetApiAdminInvitesResponses = {
  /**
   * OK
   */
  200: InternalHttpapiInvitesResponse;
};

export type GetApiAdminInvitesResponse = GetApiAdminInvitesResponses[keyof GetApiAdminInvitesResponses];

export type PostApiAdminInvitesData = {
  /**
   * Invite
   */
  body: InternalHttpapiCreateInviteRequest;
  path?: never;
  query?: never;
  url: '/api/admin/invites';
};

export type PostApiAdminInvitesErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminInvitesError = PostApiAdminInvitesErrors[keyof PostApiAdminInvitesErrors];

export type PostApiAdminInvitesResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAdminInvitesResponse = PostApiAdminInvitesResponses[keyof PostApiAdminInvitesResponses];

export type DeleteApiAdminInvitesByIdData = {
  body?: never;
  path: {
    /**
     * Invite ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/invites/{id}';
};

export type DeleteApiAdminInvitesByIdErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type DeleteApiAdminInvitesByIdError = DeleteApiAdminInvitesByIdErrors[keyof DeleteApiAdminInvitesByIdErrors];

export type DeleteApiAdminInvitesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminInvitesByIdResponse = DeleteApiAdminInvitesByIdResponses[keyof DeleteApiAdminInvitesByIdResponses];

export type PostApiAdminInvitesByIdResendData = {
  /**
   * Optional TTL override
   */
  body?: InternalHttpapiResendInviteRequest;
  path: {
    /**
     * Invite ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/invites/{id}/resend';
};

export type PostApiAdminInvitesByIdResendErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminInvitesByIdResendError = PostApiAdminInvitesByIdResendErrors[keyof PostApiAdminInvitesByIdResendErrors];

export type PostApiAdminInvitesByIdResendResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAdminInvitesByIdResendResponse = PostApiAdminInvitesByIdResendResponses[keyof PostApiAdminInvitesByIdResendResponses];

export type GetApiAdminLibrariesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/libraries';
};

export type GetApiAdminLibrariesErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminLibrariesError = GetApiAdminLibrariesErrors[keyof GetApiAdminLibrariesErrors];

export type GetApiAdminLibrariesResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLibrariesResponse;
};

export type GetApiAdminLibrariesResponse = GetApiAdminLibrariesResponses[keyof GetApiAdminLibrariesResponses];

export type PostApiAdminLibrariesData = {
  /**
   * Library fields
   */
  body: InternalHttpapiCreateLibraryRequest;
  path?: never;
  query?: never;
  url: '/api/admin/libraries';
};

export type PostApiAdminLibrariesErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminLibrariesError = PostApiAdminLibrariesErrors[keyof PostApiAdminLibrariesErrors];

export type PostApiAdminLibrariesResponses = {
  /**
   * Created
   */
  201: InternalHttpapiLibraryResponse;
};

export type PostApiAdminLibrariesResponse = PostApiAdminLibrariesResponses[keyof PostApiAdminLibrariesResponses];

export type PostApiAdminLibrariesSyncData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/libraries/sync';
};

export type PostApiAdminLibrariesSyncErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminLibrariesSyncError = PostApiAdminLibrariesSyncErrors[keyof PostApiAdminLibrariesSyncErrors];

export type PostApiAdminLibrariesSyncResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLibrariesResponse;
};

export type PostApiAdminLibrariesSyncResponse = PostApiAdminLibrariesSyncResponses[keyof PostApiAdminLibrariesSyncResponses];

export type DeleteApiAdminLibrariesByIdData = {
  body?: never;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}';
};

export type DeleteApiAdminLibrariesByIdErrors = {
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type DeleteApiAdminLibrariesByIdError = DeleteApiAdminLibrariesByIdErrors[keyof DeleteApiAdminLibrariesByIdErrors];

export type DeleteApiAdminLibrariesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminLibrariesByIdResponse = DeleteApiAdminLibrariesByIdResponses[keyof DeleteApiAdminLibrariesByIdResponses];

export type PatchApiAdminLibrariesByIdData = {
  /**
   * Library fields
   */
  body: InternalHttpapiPatchLibraryRequest;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}';
};

export type PatchApiAdminLibrariesByIdErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiAdminLibrariesByIdError = PatchApiAdminLibrariesByIdErrors[keyof PatchApiAdminLibrariesByIdErrors];

export type PatchApiAdminLibrariesByIdResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLibraryResponse;
};

export type PatchApiAdminLibrariesByIdResponse = PatchApiAdminLibrariesByIdResponses[keyof PatchApiAdminLibrariesByIdResponses];

export type GetApiAdminLibrariesByIdMaintenanceData = {
  body?: never;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}/maintenance';
};

export type GetApiAdminLibrariesByIdMaintenanceErrors = {
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type GetApiAdminLibrariesByIdMaintenanceError = GetApiAdminLibrariesByIdMaintenanceErrors[keyof GetApiAdminLibrariesByIdMaintenanceErrors];

export type GetApiAdminLibrariesByIdMaintenanceResponses = {
  /**
   * OK
   */
  200: InternalHttpapiMaintenanceStatusResponse;
};

export type GetApiAdminLibrariesByIdMaintenanceResponse = GetApiAdminLibrariesByIdMaintenanceResponses[keyof GetApiAdminLibrariesByIdMaintenanceResponses];

export type PatchApiAdminLibrariesByIdMaintenanceData = {
  /**
   * Schedules
   */
  body: InternalHttpapiPatchMaintenanceRequest;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}/maintenance';
};

export type PatchApiAdminLibrariesByIdMaintenanceErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
};

export type PatchApiAdminLibrariesByIdMaintenanceError = PatchApiAdminLibrariesByIdMaintenanceErrors[keyof PatchApiAdminLibrariesByIdMaintenanceErrors];

export type PatchApiAdminLibrariesByIdMaintenanceResponses = {
  /**
   * OK
   */
  200: InternalHttpapiMaintenanceStatusResponse;
};

export type PatchApiAdminLibrariesByIdMaintenanceResponse = PatchApiAdminLibrariesByIdMaintenanceResponses[keyof PatchApiAdminLibrariesByIdMaintenanceResponses];

export type GetApiAdminLibrariesByIdProvidersData = {
  body?: never;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}/providers';
};

export type GetApiAdminLibrariesByIdProvidersErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type GetApiAdminLibrariesByIdProvidersError = GetApiAdminLibrariesByIdProvidersErrors[keyof GetApiAdminLibrariesByIdProvidersErrors];

export type GetApiAdminLibrariesByIdProvidersResponses = {
  /**
   * OK
   */
  200: InternalHttpapiProviderSettingsResponse;
};

export type GetApiAdminLibrariesByIdProvidersResponse = GetApiAdminLibrariesByIdProvidersResponses[keyof GetApiAdminLibrariesByIdProvidersResponses];

export type PatchApiAdminLibrariesByIdProvidersData = {
  /**
   * Provider settings
   */
  body: InternalHttpapiPatchProviderSettingsRequest;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}/providers';
};

export type PatchApiAdminLibrariesByIdProvidersErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type PatchApiAdminLibrariesByIdProvidersError = PatchApiAdminLibrariesByIdProvidersErrors[keyof PatchApiAdminLibrariesByIdProvidersErrors];

export type PatchApiAdminLibrariesByIdProvidersResponses = {
  /**
   * OK
   */
  200: InternalHttpapiProviderSettingsResponse;
};

export type PatchApiAdminLibrariesByIdProvidersResponse = PatchApiAdminLibrariesByIdProvidersResponses[keyof PatchApiAdminLibrariesByIdProvidersResponses];

export type DeleteApiAdminLibrariesByIdRootsData = {
  body?: never;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query: {
    /**
     * Media-relative folder
     */
    path: string;
  };
  url: '/api/admin/libraries/{id}/roots';
};

export type DeleteApiAdminLibrariesByIdRootsErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type DeleteApiAdminLibrariesByIdRootsError = DeleteApiAdminLibrariesByIdRootsErrors[keyof DeleteApiAdminLibrariesByIdRootsErrors];

export type DeleteApiAdminLibrariesByIdRootsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLibraryResponse;
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminLibrariesByIdRootsResponse = DeleteApiAdminLibrariesByIdRootsResponses[keyof DeleteApiAdminLibrariesByIdRootsResponses];

export type PostApiAdminLibrariesByIdRootsData = {
  /**
   * Folder
   */
  body: InternalHttpapiAddLibraryRootRequest;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}/roots';
};

export type PostApiAdminLibrariesByIdRootsErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminLibrariesByIdRootsError = PostApiAdminLibrariesByIdRootsErrors[keyof PostApiAdminLibrariesByIdRootsErrors];

export type PostApiAdminLibrariesByIdRootsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLibraryResponse;
};

export type PostApiAdminLibrariesByIdRootsResponse = PostApiAdminLibrariesByIdRootsResponses[keyof PostApiAdminLibrariesByIdRootsResponses];

export type PostApiAdminLibrariesByIdSyncData = {
  body?: never;
  path: {
    /**
     * Library ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/libraries/{id}/sync';
};

export type PostApiAdminLibrariesByIdSyncErrors = {
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminLibrariesByIdSyncError = PostApiAdminLibrariesByIdSyncErrors[keyof PostApiAdminLibrariesByIdSyncErrors];

export type PostApiAdminLibrariesByIdSyncResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLibraryResponse;
};

export type PostApiAdminLibrariesByIdSyncResponse = PostApiAdminLibrariesByIdSyncResponses[keyof PostApiAdminLibrariesByIdSyncResponses];

export type GetApiAdminMaintenanceData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/maintenance';
};

export type GetApiAdminMaintenanceErrors = {
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type GetApiAdminMaintenanceError = GetApiAdminMaintenanceErrors[keyof GetApiAdminMaintenanceErrors];

export type GetApiAdminMaintenanceResponses = {
  /**
   * OK
   */
  200: InternalHttpapiMaintenanceStatusResponse;
};

export type GetApiAdminMaintenanceResponse = GetApiAdminMaintenanceResponses[keyof GetApiAdminMaintenanceResponses];

export type PatchApiAdminMaintenanceData = {
  /**
   * Schedules
   */
  body: InternalHttpapiPatchMaintenanceRequest;
  path?: never;
  query?: never;
  url: '/api/admin/maintenance';
};

export type PatchApiAdminMaintenanceErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type PatchApiAdminMaintenanceError = PatchApiAdminMaintenanceErrors[keyof PatchApiAdminMaintenanceErrors];

export type PatchApiAdminMaintenanceResponses = {
  /**
   * OK
   */
  200: InternalHttpapiMaintenanceStatusResponse;
};

export type PatchApiAdminMaintenanceResponse = PatchApiAdminMaintenanceResponses[keyof PatchApiAdminMaintenanceResponses];

export type GetApiAdminMaintenanceRunsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Max rows (default 50)
     */
    limit?: number;
  };
  url: '/api/admin/maintenance/runs';
};

export type GetApiAdminMaintenanceRunsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiMaintenanceRunsResponse;
};

export type GetApiAdminMaintenanceRunsResponse = GetApiAdminMaintenanceRunsResponses[keyof GetApiAdminMaintenanceRunsResponses];

export type PostApiAdminMaintenanceByActionRunData = {
  body?: never;
  path: {
    /**
     * Action key
     */
    action: string;
  };
  query?: {
    /**
     * Library ID (required for per-library actions)
     */
    libraryId?: string;
  };
  url: '/api/admin/maintenance/{action}/run';
};

export type PostApiAdminMaintenanceByActionRunErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
};

export type PostApiAdminMaintenanceByActionRunError = PostApiAdminMaintenanceByActionRunErrors[keyof PostApiAdminMaintenanceByActionRunErrors];

export type PostApiAdminMaintenanceByActionRunResponses = {
  /**
   * OK
   */
  200: InternalHttpapiMaintenanceRunResponse;
};

export type PostApiAdminMaintenanceByActionRunResponse = PostApiAdminMaintenanceByActionRunResponses[keyof PostApiAdminMaintenanceByActionRunResponses];

export type GetApiAdminNetworkSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/network/settings';
};

export type GetApiAdminNetworkSettingsErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminNetworkSettingsError = GetApiAdminNetworkSettingsErrors[keyof GetApiAdminNetworkSettingsErrors];

export type GetApiAdminNetworkSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalNetworkSettings;
};

export type GetApiAdminNetworkSettingsResponse = GetApiAdminNetworkSettingsResponses[keyof GetApiAdminNetworkSettingsResponses];

export type PatchApiAdminNetworkSettingsData = {
  /**
   * Network settings
   */
  body: SudoStreamInternalNetworkSettings;
  path?: never;
  query?: never;
  url: '/api/admin/network/settings';
};

export type PatchApiAdminNetworkSettingsErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiAdminNetworkSettingsError = PatchApiAdminNetworkSettingsErrors[keyof PatchApiAdminNetworkSettingsErrors];

export type PatchApiAdminNetworkSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalNetworkSettings;
};

export type PatchApiAdminNetworkSettingsResponse = PatchApiAdminNetworkSettingsResponses[keyof PatchApiAdminNetworkSettingsResponses];

export type PostApiAdminNetworkSettingsTestData = {
  /**
   * Draft network settings
   */
  body: SudoStreamInternalNetworkSettings;
  path?: never;
  query?: never;
  url: '/api/admin/network/settings/test';
};

export type PostApiAdminNetworkSettingsTestErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminNetworkSettingsTestError = PostApiAdminNetworkSettingsTestErrors[keyof PostApiAdminNetworkSettingsTestErrors];

export type PostApiAdminNetworkSettingsTestResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalNetworkProbeResult;
};

export type PostApiAdminNetworkSettingsTestResponse = PostApiAdminNetworkSettingsTestResponses[keyof PostApiAdminNetworkSettingsTestResponses];

export type DeleteApiAdminSessionsByIdData = {
  body?: never;
  path: {
    /**
     * Session ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/sessions/{id}';
};

export type DeleteApiAdminSessionsByIdErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type DeleteApiAdminSessionsByIdError = DeleteApiAdminSessionsByIdErrors[keyof DeleteApiAdminSessionsByIdErrors];

export type DeleteApiAdminSessionsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminSessionsByIdResponse = DeleteApiAdminSessionsByIdResponses[keyof DeleteApiAdminSessionsByIdResponses];

export type GetApiAdminSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/settings';
};

export type GetApiAdminSettingsErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminSettingsError = GetApiAdminSettingsErrors[keyof GetApiAdminSettingsErrors];

export type GetApiAdminSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalAuthSettings;
};

export type GetApiAdminSettingsResponse = GetApiAdminSettingsResponses[keyof GetApiAdminSettingsResponses];

export type PatchApiAdminSettingsData = {
  /**
   * Settings
   */
  body: SudoStreamInternalAuthSettings;
  path?: never;
  query?: never;
  url: '/api/admin/settings';
};

export type PatchApiAdminSettingsErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiAdminSettingsError = PatchApiAdminSettingsErrors[keyof PatchApiAdminSettingsErrors];

export type PatchApiAdminSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalAuthSettings;
};

export type PatchApiAdminSettingsResponse = PatchApiAdminSettingsResponses[keyof PatchApiAdminSettingsResponses];

export type GetApiAdminTranscodeSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/transcode/settings';
};

export type GetApiAdminTranscodeSettingsErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminTranscodeSettingsError = GetApiAdminTranscodeSettingsErrors[keyof GetApiAdminTranscodeSettingsErrors];

export type GetApiAdminTranscodeSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalTranscodeTranscodeSettings;
};

export type GetApiAdminTranscodeSettingsResponse = GetApiAdminTranscodeSettingsResponses[keyof GetApiAdminTranscodeSettingsResponses];

export type PatchApiAdminTranscodeSettingsData = {
  /**
   * Transcode settings
   */
  body: SudoStreamInternalTranscodeTranscodeSettings;
  path?: never;
  query?: never;
  url: '/api/admin/transcode/settings';
};

export type PatchApiAdminTranscodeSettingsErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiAdminTranscodeSettingsError = PatchApiAdminTranscodeSettingsErrors[keyof PatchApiAdminTranscodeSettingsErrors];

export type PatchApiAdminTranscodeSettingsResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalTranscodeTranscodeSettings;
};

export type PatchApiAdminTranscodeSettingsResponse = PatchApiAdminTranscodeSettingsResponses[keyof PatchApiAdminTranscodeSettingsResponses];

export type DeleteApiAdminTrashData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/trash';
};

export type DeleteApiAdminTrashErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type DeleteApiAdminTrashError = DeleteApiAdminTrashErrors[keyof DeleteApiAdminTrashErrors];

export type DeleteApiAdminTrashResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminTrashResponse = DeleteApiAdminTrashResponses[keyof DeleteApiAdminTrashResponses];

export type GetApiAdminTrashData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/trash';
};

export type GetApiAdminTrashErrors = {
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type GetApiAdminTrashError = GetApiAdminTrashErrors[keyof GetApiAdminTrashErrors];

export type GetApiAdminTrashResponses = {
  /**
   * OK
   */
  200: InternalHttpapiTrashListResponse;
};

export type GetApiAdminTrashResponse = GetApiAdminTrashResponses[keyof GetApiAdminTrashResponses];

export type GetApiAdminTrashSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/trash/settings';
};

export type GetApiAdminTrashSettingsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiTrashSettingsResponse;
};

export type GetApiAdminTrashSettingsResponse = GetApiAdminTrashSettingsResponses[keyof GetApiAdminTrashSettingsResponses];

export type PatchApiAdminTrashSettingsData = {
  /**
   * Recycle bin settings
   */
  body: InternalHttpapiTrashSettingsResponse;
  path?: never;
  query?: never;
  url: '/api/admin/trash/settings';
};

export type PatchApiAdminTrashSettingsErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
};

export type PatchApiAdminTrashSettingsError = PatchApiAdminTrashSettingsErrors[keyof PatchApiAdminTrashSettingsErrors];

export type PatchApiAdminTrashSettingsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiTrashSettingsResponse;
};

export type PatchApiAdminTrashSettingsResponse = PatchApiAdminTrashSettingsResponses[keyof PatchApiAdminTrashSettingsResponses];

export type DeleteApiAdminTrashByIdData = {
  body?: never;
  path: {
    /**
     * Trash item id
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/trash/{id}';
};

export type DeleteApiAdminTrashByIdErrors = {
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
};

export type DeleteApiAdminTrashByIdError = DeleteApiAdminTrashByIdErrors[keyof DeleteApiAdminTrashByIdErrors];

export type DeleteApiAdminTrashByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminTrashByIdResponse = DeleteApiAdminTrashByIdResponses[keyof DeleteApiAdminTrashByIdResponses];

export type PostApiAdminTrashByIdRestoreData = {
  body?: never;
  path: {
    /**
     * Trash item id
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/trash/{id}/restore';
};

export type PostApiAdminTrashByIdRestoreErrors = {
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
};

export type PostApiAdminTrashByIdRestoreError = PostApiAdminTrashByIdRestoreErrors[keyof PostApiAdminTrashByIdRestoreErrors];

export type PostApiAdminTrashByIdRestoreResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalTrashItem;
};

export type PostApiAdminTrashByIdRestoreResponse = PostApiAdminTrashByIdRestoreResponses[keyof PostApiAdminTrashByIdRestoreResponses];

export type GetApiAdminUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/users';
};

export type GetApiAdminUsersErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminUsersError = GetApiAdminUsersErrors[keyof GetApiAdminUsersErrors];

export type GetApiAdminUsersResponses = {
  /**
   * OK
   */
  200: InternalHttpapiUsersResponse;
};

export type GetApiAdminUsersResponse = GetApiAdminUsersResponses[keyof GetApiAdminUsersResponses];

export type PostApiAdminUsersData = {
  /**
   * New user
   */
  body: InternalHttpapiCreateUserRequest;
  path?: never;
  query?: never;
  url: '/api/admin/users';
};

export type PostApiAdminUsersErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminUsersError = PostApiAdminUsersErrors[keyof PostApiAdminUsersErrors];

export type PostApiAdminUsersResponses = {
  /**
   * Created
   */
  201: InternalHttpapiUserResponse;
};

export type PostApiAdminUsersResponse = PostApiAdminUsersResponses[keyof PostApiAdminUsersResponses];

export type DeleteApiAdminUsersByIdData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}';
};

export type DeleteApiAdminUsersByIdErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type DeleteApiAdminUsersByIdError = DeleteApiAdminUsersByIdErrors[keyof DeleteApiAdminUsersByIdErrors];

export type DeleteApiAdminUsersByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminUsersByIdResponse = DeleteApiAdminUsersByIdResponses[keyof DeleteApiAdminUsersByIdResponses];

export type PatchApiAdminUsersByIdData = {
  /**
   * User patch
   */
  body: InternalHttpapiUpdateUserRequest;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}';
};

export type PatchApiAdminUsersByIdErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiAdminUsersByIdError = PatchApiAdminUsersByIdErrors[keyof PatchApiAdminUsersByIdErrors];

export type PatchApiAdminUsersByIdResponses = {
  /**
   * OK
   */
  200: InternalHttpapiAdminUserResponse;
};

export type PatchApiAdminUsersByIdResponse = PatchApiAdminUsersByIdResponses[keyof PatchApiAdminUsersByIdResponses];

export type PostApiAdminUsersById2FaResetData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/2fa/reset';
};

export type PostApiAdminUsersById2FaResetErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminUsersById2FaResetError = PostApiAdminUsersById2FaResetErrors[keyof PostApiAdminUsersById2FaResetErrors];

export type PostApiAdminUsersById2FaResetResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAdminUsersById2FaResetResponse = PostApiAdminUsersById2FaResetResponses[keyof PostApiAdminUsersById2FaResetResponses];

export type GetApiAdminUsersByIdLibrariesData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/libraries';
};

export type GetApiAdminUsersByIdLibrariesErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminUsersByIdLibrariesError = GetApiAdminUsersByIdLibrariesErrors[keyof GetApiAdminUsersByIdLibrariesErrors];

export type GetApiAdminUsersByIdLibrariesResponses = {
  /**
   * OK
   */
  200: InternalHttpapiGrantsResponse;
};

export type GetApiAdminUsersByIdLibrariesResponse = GetApiAdminUsersByIdLibrariesResponses[keyof GetApiAdminUsersByIdLibrariesResponses];

export type PutApiAdminUsersByIdLibrariesData = {
  /**
   * Grant list
   */
  body: InternalHttpapiPutGrantsRequest;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/libraries';
};

export type PutApiAdminUsersByIdLibrariesErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PutApiAdminUsersByIdLibrariesError = PutApiAdminUsersByIdLibrariesErrors[keyof PutApiAdminUsersByIdLibrariesErrors];

export type PutApiAdminUsersByIdLibrariesResponses = {
  /**
   * OK
   */
  200: InternalHttpapiGrantsResponse;
};

export type PutApiAdminUsersByIdLibrariesResponse = PutApiAdminUsersByIdLibrariesResponses[keyof PutApiAdminUsersByIdLibrariesResponses];

export type PostApiAdminUsersByIdResendConfirmData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/resend-confirm';
};

export type PostApiAdminUsersByIdResendConfirmErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminUsersByIdResendConfirmError = PostApiAdminUsersByIdResendConfirmErrors[keyof PostApiAdminUsersByIdResendConfirmErrors];

export type PostApiAdminUsersByIdResendConfirmResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAdminUsersByIdResendConfirmResponse = PostApiAdminUsersByIdResendConfirmResponses[keyof PostApiAdminUsersByIdResendConfirmResponses];

export type GetApiAdminUsersByIdSessionsData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/sessions';
};

export type GetApiAdminUsersByIdSessionsErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAdminUsersByIdSessionsError = GetApiAdminUsersByIdSessionsErrors[keyof GetApiAdminUsersByIdSessionsErrors];

export type GetApiAdminUsersByIdSessionsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiSessionsResponse;
};

export type GetApiAdminUsersByIdSessionsResponse = GetApiAdminUsersByIdSessionsResponses[keyof GetApiAdminUsersByIdSessionsResponses];

export type PostApiAdminUsersByIdSessionsRevokeAllData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: '/api/admin/users/{id}/sessions/revoke-all';
};

export type PostApiAdminUsersByIdSessionsRevokeAllErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAdminUsersByIdSessionsRevokeAllError = PostApiAdminUsersByIdSessionsRevokeAllErrors[keyof PostApiAdminUsersByIdSessionsRevokeAllErrors];

export type PostApiAdminUsersByIdSessionsRevokeAllResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAdminUsersByIdSessionsRevokeAllResponse = PostApiAdminUsersByIdSessionsRevokeAllResponses[keyof PostApiAdminUsersByIdSessionsRevokeAllResponses];

export type DeleteApiAuth2FaData = {
  /**
   * Password and TOTP code
   */
  body: InternalHttpapiDisableTwoFactorRequest;
  path?: never;
  query?: never;
  url: '/api/auth/2fa';
};

export type DeleteApiAuth2FaErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
};

export type DeleteApiAuth2FaError = DeleteApiAuth2FaErrors[keyof DeleteApiAuth2FaErrors];

export type DeleteApiAuth2FaResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAuth2FaResponse = DeleteApiAuth2FaResponses[keyof DeleteApiAuth2FaResponses];

export type PostApiAuth2FaConfirmData = {
  /**
   * TOTP code
   */
  body: InternalHttpapiTwoFactorConfirmRequest;
  path?: never;
  query?: never;
  url: '/api/auth/2fa/confirm';
};

export type PostApiAuth2FaConfirmErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
};

export type PostApiAuth2FaConfirmError = PostApiAuth2FaConfirmErrors[keyof PostApiAuth2FaConfirmErrors];

export type PostApiAuth2FaConfirmResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalAuthTwoFactorConfirmResult;
};

export type PostApiAuth2FaConfirmResponse = PostApiAuth2FaConfirmResponses[keyof PostApiAuth2FaConfirmResponses];

export type PostApiAuth2FaSetupData = {
  /**
   * Optional pending token
   */
  body?: InternalHttpapiTwoFactorSetupRequest;
  path?: never;
  query?: never;
  url: '/api/auth/2fa/setup';
};

export type PostApiAuth2FaSetupErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
};

export type PostApiAuth2FaSetupError = PostApiAuth2FaSetupErrors[keyof PostApiAuth2FaSetupErrors];

export type PostApiAuth2FaSetupResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalAuthTwoFactorSetup;
};

export type PostApiAuth2FaSetupResponse = PostApiAuth2FaSetupResponses[keyof PostApiAuth2FaSetupResponses];

export type PostApiAuth2FaVerifyData = {
  /**
   * Pending token and code
   */
  body: InternalHttpapiVerifyTwoFactorRequest;
  path?: never;
  query?: never;
  url: '/api/auth/2fa/verify';
};

export type PostApiAuth2FaVerifyErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
};

export type PostApiAuth2FaVerifyError = PostApiAuth2FaVerifyErrors[keyof PostApiAuth2FaVerifyErrors];

export type PostApiAuth2FaVerifyResponses = {
  /**
   * OK
   */
  200: InternalHttpapiAuthTokensResponse;
};

export type PostApiAuth2FaVerifyResponse = PostApiAuth2FaVerifyResponses[keyof PostApiAuth2FaVerifyResponses];

export type PostApiAuthAcceptInviteData = {
  /**
   * Invite token
   */
  body: InternalHttpapiAcceptInviteRequest;
  path?: never;
  query?: never;
  url: '/api/auth/accept-invite';
};

export type PostApiAuthAcceptInviteErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
};

export type PostApiAuthAcceptInviteError = PostApiAuthAcceptInviteErrors[keyof PostApiAuthAcceptInviteErrors];

export type PostApiAuthAcceptInviteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAuthAcceptInviteResponse = PostApiAuthAcceptInviteResponses[keyof PostApiAuthAcceptInviteResponses];

export type PostApiAuthChangeEmailData = {
  /**
   * Email change
   */
  body: InternalHttpapiChangeEmailRequest;
  path?: never;
  query?: never;
  url: '/api/auth/change-email';
};

export type PostApiAuthChangeEmailErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAuthChangeEmailError = PostApiAuthChangeEmailErrors[keyof PostApiAuthChangeEmailErrors];

export type PostApiAuthChangeEmailResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAuthChangeEmailResponse = PostApiAuthChangeEmailResponses[keyof PostApiAuthChangeEmailResponses];

export type PostApiAuthChangePasswordData = {
  /**
   * Password change
   */
  body: InternalHttpapiChangePasswordRequest;
  path?: never;
  query?: never;
  url: '/api/auth/change-password';
};

export type PostApiAuthChangePasswordErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAuthChangePasswordError = PostApiAuthChangePasswordErrors[keyof PostApiAuthChangePasswordErrors];

export type PostApiAuthChangePasswordResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLoginResponse;
};

export type PostApiAuthChangePasswordResponse = PostApiAuthChangePasswordResponses[keyof PostApiAuthChangePasswordResponses];

export type GetApiAuthConfirmEmailData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Confirmation token
     */
    token: string;
  };
  url: '/api/auth/confirm-email';
};

export type GetApiAuthConfirmEmailErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
};

export type GetApiAuthConfirmEmailError = GetApiAuthConfirmEmailErrors[keyof GetApiAuthConfirmEmailErrors];

export type GetApiAuthConfirmEmailResponses = {
  /**
   * OK
   */
  200: InternalHttpapiStatusResponse;
};

export type GetApiAuthConfirmEmailResponse = GetApiAuthConfirmEmailResponses[keyof GetApiAuthConfirmEmailResponses];

export type PostApiAuthForgotPasswordData = {
  /**
   * Email
   */
  body: InternalHttpapiForgotPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/auth/forgot-password';
};

export type PostApiAuthForgotPasswordErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
};

export type PostApiAuthForgotPasswordError = PostApiAuthForgotPasswordErrors[keyof PostApiAuthForgotPasswordErrors];

export type PostApiAuthForgotPasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAuthForgotPasswordResponse = PostApiAuthForgotPasswordResponses[keyof PostApiAuthForgotPasswordResponses];

export type PostApiAuthLoginData = {
  /**
   * Credentials
   */
  body: InternalHttpapiLoginRequest;
  path?: never;
  query?: never;
  url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type PostApiAuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
};

export type PostApiAuthLogoutError = PostApiAuthLogoutErrors[keyof PostApiAuthLogoutErrors];

export type PostApiAuthLogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAuthLogoutResponse = PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type GetApiAuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/me';
};

export type GetApiAuthMeErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
};

export type GetApiAuthMeError = GetApiAuthMeErrors[keyof GetApiAuthMeErrors];

export type GetApiAuthMeResponses = {
  /**
   * OK
   */
  200: InternalHttpapiMeResponse;
};

export type GetApiAuthMeResponse = GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type PostApiAuthRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/refresh';
};

export type PostApiAuthRefreshErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
};

export type PostApiAuthRefreshError = PostApiAuthRefreshErrors[keyof PostApiAuthRefreshErrors];

export type PostApiAuthRefreshResponses = {
  /**
   * OK
   */
  200: InternalHttpapiRefreshResponse;
};

export type PostApiAuthRefreshResponse = PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type PostApiAuthResetPasswordData = {
  /**
   * Reset token
   */
  body: InternalHttpapiResetPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/auth/reset-password';
};

export type PostApiAuthResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
};

export type PostApiAuthResetPasswordError = PostApiAuthResetPasswordErrors[keyof PostApiAuthResetPasswordErrors];

export type PostApiAuthResetPasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAuthResetPasswordResponse = PostApiAuthResetPasswordResponses[keyof PostApiAuthResetPasswordResponses];

export type GetApiAuthSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/sessions';
};

export type GetApiAuthSessionsErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiAuthSessionsError = GetApiAuthSessionsErrors[keyof GetApiAuthSessionsErrors];

export type GetApiAuthSessionsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiSessionsResponse;
};

export type GetApiAuthSessionsResponse = GetApiAuthSessionsResponses[keyof GetApiAuthSessionsResponses];

export type PostApiAuthSessionsRevokeAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/sessions/revoke-all';
};

export type PostApiAuthSessionsRevokeAllErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiAuthSessionsRevokeAllError = PostApiAuthSessionsRevokeAllErrors[keyof PostApiAuthSessionsRevokeAllErrors];

export type PostApiAuthSessionsRevokeAllResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAuthSessionsRevokeAllResponse = PostApiAuthSessionsRevokeAllResponses[keyof PostApiAuthSessionsRevokeAllResponses];

export type DeleteApiAuthSessionsByIdData = {
  body?: never;
  path: {
    /**
     * Session ID
     */
    id: string;
  };
  query?: never;
  url: '/api/auth/sessions/{id}';
};

export type DeleteApiAuthSessionsByIdErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type DeleteApiAuthSessionsByIdError = DeleteApiAuthSessionsByIdErrors[keyof DeleteApiAuthSessionsByIdErrors];

export type DeleteApiAuthSessionsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAuthSessionsByIdResponse = DeleteApiAuthSessionsByIdResponses[keyof DeleteApiAuthSessionsByIdResponses];

export type GetApiBrowseData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page size (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/browse';
};

export type GetApiBrowseErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiBrowseError = GetApiBrowseErrors[keyof GetApiBrowseErrors];

export type GetApiBrowseResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalMediafsBrowseResponse;
};

export type GetApiBrowseResponse = GetApiBrowseResponses[keyof GetApiBrowseResponses];

export type GetApiBrowseByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: {
    /**
     * Page size (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/browse/{path}';
};

export type GetApiBrowseByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiBrowseByPathError = GetApiBrowseByPathErrors[keyof GetApiBrowseByPathErrors];

export type GetApiBrowseByPathResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalMediafsBrowseResponse;
};

export type GetApiBrowseByPathResponse = GetApiBrowseByPathResponses[keyof GetApiBrowseByPathResponses];

export type GetApiCatalogByLibrarySlugData = {
  body?: never;
  path: {
    /**
     * Library slug
     */
    librarySlug: string;
  };
  query?: {
    /**
     * Page size (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/catalog/{librarySlug}';
};

export type GetApiCatalogByLibrarySlugErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
};

export type GetApiCatalogByLibrarySlugError = GetApiCatalogByLibrarySlugErrors[keyof GetApiCatalogByLibrarySlugErrors];

export type GetApiCatalogByLibrarySlugResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalCatalogLibraryCatalog;
};

export type GetApiCatalogByLibrarySlugResponse = GetApiCatalogByLibrarySlugResponses[keyof GetApiCatalogByLibrarySlugResponses];

export type GetApiCatalogByLibrarySlugShowsByShowKeyData = {
  body?: never;
  path: {
    /**
     * Library slug
     */
    librarySlug: string;
    /**
     * Normalized show key
     */
    showKey: string;
  };
  query?: never;
  url: '/api/catalog/{librarySlug}/shows/{showKey}';
};

export type GetApiCatalogByLibrarySlugShowsByShowKeyErrors = {
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
};

export type GetApiCatalogByLibrarySlugShowsByShowKeyError = GetApiCatalogByLibrarySlugShowsByShowKeyErrors[keyof GetApiCatalogByLibrarySlugShowsByShowKeyErrors];

export type GetApiCatalogByLibrarySlugShowsByShowKeyResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalCatalogShowDetail;
};

export type GetApiCatalogByLibrarySlugShowsByShowKeyResponse = GetApiCatalogByLibrarySlugShowsByShowKeyResponses[keyof GetApiCatalogByLibrarySlugShowsByShowKeyResponses];

export type GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesData = {
  body?: never;
  path: {
    /**
     * Library slug
     */
    librarySlug: string;
    /**
     * Normalized show key
     */
    showKey: string;
    /**
     * Season number (0 = specials)
     */
    season: number;
  };
  query?: {
    /**
     * Optional page size (omit for full season; max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/catalog/{librarySlug}/shows/{showKey}/seasons/{season}/episodes';
};

export type GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
};

export type GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesError = GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesErrors[keyof GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesErrors];

export type GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalCatalogSeasonEpisodes;
};

export type GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesResponse = GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesResponses[keyof GetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesResponses];

export type GetApiDownloadByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/download/{path}';
};

export type GetApiDownloadByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiDownloadByPathError = GetApiDownloadByPathErrors[keyof GetApiDownloadByPathErrors];

export type GetApiDownloadByPathResponses = {
  /**
   * OK
   */
  200: Blob | File;
};

export type GetApiDownloadByPathResponse = GetApiDownloadByPathResponses[keyof GetApiDownloadByPathResponses];

export type GetApiFavoriteByPathData = {
  body?: never;
  path: {
    /**
     * Media file path
     */
    path: string;
  };
  query?: never;
  url: '/api/favorite/{path}';
};

export type GetApiFavoriteByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiFavoriteByPathError = GetApiFavoriteByPathErrors[keyof GetApiFavoriteByPathErrors];

export type GetApiFavoriteByPathResponses = {
  /**
   * OK
   */
  200: InternalHttpapiFavoriteResponse;
};

export type GetApiFavoriteByPathResponse = GetApiFavoriteByPathResponses[keyof GetApiFavoriteByPathResponses];

export type PatchApiFavoriteByPathData = {
  /**
   * Favorite flag
   */
  body: InternalHttpapiFavoritePatchRequest;
  path: {
    /**
     * Media file path
     */
    path: string;
  };
  query?: never;
  url: '/api/favorite/{path}';
};

export type PatchApiFavoriteByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiFavoriteByPathError = PatchApiFavoriteByPathErrors[keyof PatchApiFavoriteByPathErrors];

export type PatchApiFavoriteByPathResponses = {
  /**
   * OK
   */
  200: InternalHttpapiFavoriteResponse;
};

export type PatchApiFavoriteByPathResponse = PatchApiFavoriteByPathResponses[keyof PatchApiFavoriteByPathResponses];

export type GetApiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type GetApiHealthErrors = {
  /**
   * Service Unavailable
   */
  503: InternalHttpapiHealthResponse;
};

export type GetApiHealthError = GetApiHealthErrors[keyof GetApiHealthErrors];

export type GetApiHealthResponses = {
  /**
   * OK
   */
  200: InternalHttpapiHealthResponse;
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetApiLibrariesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/libraries';
};

export type GetApiLibrariesErrors = {
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiLibrariesError = GetApiLibrariesErrors[keyof GetApiLibrariesErrors];

export type GetApiLibrariesResponses = {
  /**
   * OK
   */
  200: InternalHttpapiLibrariesResponse;
};

export type GetApiLibrariesResponse = GetApiLibrariesResponses[keyof GetApiLibrariesResponses];

export type GetApiMeContinueData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum items (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/me/continue';
};

export type GetApiMeContinueErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiMeContinueError = GetApiMeContinueErrors[keyof GetApiMeContinueErrors];

export type GetApiMeContinueResponses = {
  /**
   * OK
   */
  200: InternalHttpapiHomeItemsResponse;
};

export type GetApiMeContinueResponse = GetApiMeContinueResponses[keyof GetApiMeContinueResponses];

export type GetApiMeFavoritesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum items (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/me/favorites';
};

export type GetApiMeFavoritesErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiMeFavoritesError = GetApiMeFavoritesErrors[keyof GetApiMeFavoritesErrors];

export type GetApiMeFavoritesResponses = {
  /**
   * OK
   */
  200: InternalHttpapiHomeItemsResponse;
};

export type GetApiMeFavoritesResponse = GetApiMeFavoritesResponses[keyof GetApiMeFavoritesResponses];

export type GetApiMeStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/me/stats';
};

export type GetApiMeStatsErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiMeStatsError = GetApiMeStatsErrors[keyof GetApiMeStatsErrors];

export type GetApiMeStatsResponses = {
  /**
   * OK
   */
  200: InternalHttpapiHomeStatsResponse;
};

export type GetApiMeStatsResponse = GetApiMeStatsResponses[keyof GetApiMeStatsResponses];

export type GetApiMeUnwatchedData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum items (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/me/unwatched';
};

export type GetApiMeUnwatchedErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiMeUnwatchedError = GetApiMeUnwatchedErrors[keyof GetApiMeUnwatchedErrors];

export type GetApiMeUnwatchedResponses = {
  /**
   * OK
   */
  200: InternalHttpapiHomeItemsResponse;
};

export type GetApiMeUnwatchedResponse = GetApiMeUnwatchedResponses[keyof GetApiMeUnwatchedResponses];

export type GetApiMeWatchedData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum items (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/me/watched';
};

export type GetApiMeWatchedErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiMeWatchedError = GetApiMeWatchedErrors[keyof GetApiMeWatchedErrors];

export type GetApiMeWatchedResponses = {
  /**
   * OK
   */
  200: InternalHttpapiHomeItemsResponse;
};

export type GetApiMeWatchedResponse = GetApiMeWatchedResponses[keyof GetApiMeWatchedResponses];

export type DeleteApiMediaByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: {
    /**
     * Ignored for recycle-bin deletes; directories always move as a tree
     */
    recursive?: boolean;
  };
  url: '/api/media/{path}';
};

export type DeleteApiMediaByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Conflict
   */
  409: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type DeleteApiMediaByPathError = DeleteApiMediaByPathErrors[keyof DeleteApiMediaByPathErrors];

export type DeleteApiMediaByPathResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiMediaByPathResponse = DeleteApiMediaByPathResponses[keyof DeleteApiMediaByPathResponses];

export type GetApiMetadataByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/metadata/{path}';
};

export type GetApiMetadataByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiMetadataByPathError = GetApiMetadataByPathErrors[keyof GetApiMetadataByPathErrors];

export type GetApiMetadataByPathResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalMetadataMetadataResponse;
};

export type GetApiMetadataByPathResponse = GetApiMetadataByPathResponses[keyof GetApiMetadataByPathResponses];

export type PatchApiMetadataByPathData = {
  /**
   * Metadata patch
   */
  body: SudoStreamInternalMetadataPatchRequest;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/metadata/{path}';
};

export type PatchApiMetadataByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiMetadataByPathError = PatchApiMetadataByPathErrors[keyof PatchApiMetadataByPathErrors];

export type PatchApiMetadataByPathResponses = {
  /**
   * OK
   */
  200: SudoStreamInternalMetadataMetadataResponse;
};

export type PatchApiMetadataByPathResponse = PatchApiMetadataByPathResponses[keyof PatchApiMetadataByPathResponses];

export type PostApiOauthTokenData = {
  body?: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: '/api/oauth/token';
};

export type PostApiOauthTokenErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiOAuthErrorResponse;
  /**
   * Unauthorized
   */
  401: InternalHttpapiOAuthErrorResponse;
};

export type PostApiOauthTokenError = PostApiOauthTokenErrors[keyof PostApiOauthTokenErrors];

export type PostApiOauthTokenResponses = {
  /**
   * OK
   */
  200: InternalHttpapiOAuthTokenResponse;
};

export type PostApiOauthTokenResponse = PostApiOauthTokenResponses[keyof PostApiOauthTokenResponses];

export type GetApiPlayByPathData = {
  body?: never;
  path: {
    /**
     * Media file path with optional HLS resource suffix
     */
    path: string;
  };
  query?: never;
  url: '/api/play/{path}';
};

export type GetApiPlayByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
  /**
   * Service Unavailable
   */
  503: InternalHttpapiErrorResponse;
};

export type GetApiPlayByPathError = GetApiPlayByPathErrors[keyof GetApiPlayByPathErrors];

export type GetApiPlayByPathResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetApiPlayByPathResponse = GetApiPlayByPathResponses[keyof GetApiPlayByPathResponses];

export type GetApiPlaybackByPathData = {
  body?: never;
  path: {
    /**
     * Media file path
     */
    path: string;
  };
  query?: {
    /**
     * Start HLS transcode job
     */
    transcode?: boolean;
    /**
     * Start transcode after direct playback failed
     */
    fallback?: boolean;
  };
  url: '/api/playback/{path}';
};

export type GetApiPlaybackByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiPlaybackByPathError = GetApiPlaybackByPathErrors[keyof GetApiPlaybackByPathErrors];

export type GetApiPlaybackByPathResponses = {
  /**
   * OK
   */
  200: InternalHttpapiPlaybackResponse;
};

export type GetApiPlaybackByPathResponse = GetApiPlaybackByPathResponses[keyof GetApiPlaybackByPathResponses];

export type PostApiPlaybackByPathData = {
  /**
   * Device profile and quality selection
   */
  body?: InternalHttpapiPlaybackNegotiateRequest;
  path: {
    /**
     * Media file path
     */
    path: string;
  };
  query?: never;
  url: '/api/playback/{path}';
};

export type PostApiPlaybackByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PostApiPlaybackByPathError = PostApiPlaybackByPathErrors[keyof PostApiPlaybackByPathErrors];

export type PostApiPlaybackByPathResponses = {
  /**
   * OK
   */
  200: InternalHttpapiPlaybackResponse;
};

export type PostApiPlaybackByPathResponse = PostApiPlaybackByPathResponses[keyof PostApiPlaybackByPathResponses];

export type GetApiProviderPosterByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/provider-poster/{path}';
};

export type GetApiProviderPosterByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiProviderPosterByPathError = GetApiProviderPosterByPathErrors[keyof GetApiProviderPosterByPathErrors];

export type GetApiProviderPosterByPathResponses = {
  /**
   * OK
   */
  200: Blob | File;
};

export type GetApiProviderPosterByPathResponse = GetApiProviderPosterByPathResponses[keyof GetApiProviderPosterByPathResponses];

export type GetApiProviderSubtitleByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query: {
    /**
     * ISO 639-1 language code
     */
    lang: string;
  };
  url: '/api/provider-subtitle/{path}';
};

export type GetApiProviderSubtitleByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiProviderSubtitleByPathError = GetApiProviderSubtitleByPathErrors[keyof GetApiProviderSubtitleByPathErrors];

export type GetApiProviderSubtitleByPathResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetApiProviderSubtitleByPathResponse = GetApiProviderSubtitleByPathResponses[keyof GetApiProviderSubtitleByPathResponses];

export type GetApiSearchData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Search query
     */
    q: string;
    /**
     * Page size (default 28, max 100)
     */
    limit?: number;
    /**
     * Offset (default 0)
     */
    offset?: number;
  };
  url: '/api/search';
};

export type GetApiSearchErrors = {
  /**
   * Unauthorized
   */
  401: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiSearchError = GetApiSearchErrors[keyof GetApiSearchErrors];

export type GetApiSearchResponses = {
  /**
   * OK
   */
  200: InternalHttpapiSearchResponse;
};

export type GetApiSearchResponse = GetApiSearchResponses[keyof GetApiSearchResponses];

export type GetApiStreamByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/stream/{path}';
};

export type GetApiStreamByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiStreamByPathError = GetApiStreamByPathErrors[keyof GetApiStreamByPathErrors];

export type GetApiStreamByPathResponses = {
  /**
   * OK
   */
  200: Blob | File;
  /**
   * Partial Content
   */
  206: Blob | File;
};

export type GetApiStreamByPathResponse = GetApiStreamByPathResponses[keyof GetApiStreamByPathResponses];

export type GetApiThumbnailByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: {
    /**
     * Thumbnail width (images only)
     */
    w?: number;
    /**
     * Thumbnail height (images only)
     */
    h?: number;
  };
  url: '/api/thumbnail/{path}';
};

export type GetApiThumbnailByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiThumbnailByPathError = GetApiThumbnailByPathErrors[keyof GetApiThumbnailByPathErrors];

export type GetApiThumbnailByPathResponses = {
  /**
   * OK
   */
  200: Blob | File;
};

export type GetApiThumbnailByPathResponse = GetApiThumbnailByPathResponses[keyof GetApiThumbnailByPathResponses];

export type DeleteApiUserSubtitleByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/user-subtitle/{path}';
};

export type DeleteApiUserSubtitleByPathErrors = {
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
};

export type DeleteApiUserSubtitleByPathError = DeleteApiUserSubtitleByPathErrors[keyof DeleteApiUserSubtitleByPathErrors];

export type DeleteApiUserSubtitleByPathResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiUserSubtitleByPathResponse = DeleteApiUserSubtitleByPathResponses[keyof DeleteApiUserSubtitleByPathResponses];

export type GetApiUserSubtitleByPathData = {
  body?: never;
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/user-subtitle/{path}';
};

export type GetApiUserSubtitleByPathErrors = {
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
};

export type GetApiUserSubtitleByPathError = GetApiUserSubtitleByPathErrors[keyof GetApiUserSubtitleByPathErrors];

export type GetApiUserSubtitleByPathResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetApiUserSubtitleByPathResponse = GetApiUserSubtitleByPathResponses[keyof GetApiUserSubtitleByPathResponses];

export type PutApiUserSubtitleByPathData = {
  /**
   * ISO 639-1 language code
   */
  body: {
    /**
     * Subtitle file (.vtt or .srt)
     */
    file: Blob | File;
    /**
     * Display label
     */
    label?: string;
    /**
     * ISO 639-1 language code
     */
    lang?: string;
  };
  path: {
    /**
     * Path under media root
     */
    path: string;
  };
  query?: never;
  url: '/api/user-subtitle/{path}';
};

export type PutApiUserSubtitleByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Request Entity Too Large
   */
  413: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PutApiUserSubtitleByPathError = PutApiUserSubtitleByPathErrors[keyof PutApiUserSubtitleByPathErrors];

export type PutApiUserSubtitleByPathResponses = {
  /**
   * OK
   */
  200: InternalHttpapiUserSubtitleTrack;
};

export type PutApiUserSubtitleByPathResponse = PutApiUserSubtitleByPathResponses[keyof PutApiUserSubtitleByPathResponses];

export type GetApiWatchByPathData = {
  body?: never;
  path: {
    /**
     * Media file path
     */
    path: string;
  };
  query?: never;
  url: '/api/watch/{path}';
};

export type GetApiWatchByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type GetApiWatchByPathError = GetApiWatchByPathErrors[keyof GetApiWatchByPathErrors];

export type GetApiWatchByPathResponses = {
  /**
   * OK
   */
  200: InternalHttpapiWatchResponse;
};

export type GetApiWatchByPathResponse = GetApiWatchByPathResponses[keyof GetApiWatchByPathResponses];

export type PatchApiWatchByPathData = {
  /**
   * Watched flag and optional progress
   */
  body: InternalHttpapiWatchPatchRequest;
  path: {
    /**
     * Media file path
     */
    path: string;
  };
  query?: never;
  url: '/api/watch/{path}';
};

export type PatchApiWatchByPathErrors = {
  /**
   * Bad Request
   */
  400: InternalHttpapiErrorResponse;
  /**
   * Forbidden
   */
  403: InternalHttpapiErrorResponse;
  /**
   * Not Found
   */
  404: InternalHttpapiErrorResponse;
  /**
   * Internal Server Error
   */
  500: InternalHttpapiErrorResponse;
};

export type PatchApiWatchByPathError = PatchApiWatchByPathErrors[keyof PatchApiWatchByPathErrors];

export type PatchApiWatchByPathResponses = {
  /**
   * OK
   */
  200: InternalHttpapiWatchResponse;
};

export type PatchApiWatchByPathResponse = PatchApiWatchByPathResponses[keyof PatchApiWatchByPathResponses];

export type GetMetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/metrics';
};

export type GetMetricsResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetMetricsResponse = GetMetricsResponses[keyof GetMetricsResponses];
