// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zInternalHttpapiAcceptInviteRequest = z.object({
  password: z.string().optional(),
  token: z.string().optional()
});

export const zInternalHttpapiAddLibraryRootRequest = z.object({
  relPath: z.string().optional()
});

export const zInternalHttpapiChangeEmailRequest = z.object({
  newEmail: z.string().optional(),
  password: z.string().optional(),
  totp: z.string().optional()
});

export const zInternalHttpapiChangePasswordRequest = z.object({
  currentPassword: z.string().optional(),
  newPassword: z.string().optional(),
  totp: z.string().optional()
});

export const zInternalHttpapiCreateInviteRequest = z.object({
  email: z.string().optional(),
  expiresInHours: z.int().optional(),
  role: z.string().optional()
});

export const zInternalHttpapiCreateLibraryRequest = z.object({
  name: z.string().optional(),
  slug: z.string().optional(),
  type: z.string().optional()
});

export const zInternalHttpapiCreateUserRequest = z.object({
  email: z.string().optional(),
  password: z.string().optional(),
  role: z.string().optional()
});

export const zInternalHttpapiDisableTwoFactorRequest = z.object({
  code: z.string().optional(),
  password: z.string().optional()
});

export const zInternalHttpapiErrorResponse = z.object({
  error: z.string().optional()
});

export const zInternalHttpapiFavoritePatchRequest = z.object({
  favorited: z.boolean().optional()
});

export const zInternalHttpapiFavoriteResponse = z.object({
  favorited: z.boolean().optional()
});

export const zInternalHttpapiFolderTreeEntry = z.object({
  assignedLibraryId: z.string().optional(),
  name: z.string().optional(),
  relPath: z.string().optional()
});

export const zInternalHttpapiFolderTreeResponse = z.object({
  entries: z.array(zInternalHttpapiFolderTreeEntry).optional(),
  path: z.string().optional()
});

export const zInternalHttpapiForgotPasswordRequest = z.object({
  email: z.string().optional()
});

export const zInternalHttpapiHealthResponse = z.object({
  status: z.string().optional(),
  version: z.string().optional()
});

export const zInternalHttpapiLoginRequest = z.object({
  email: z.string().optional(),
  password: z.string().optional()
});

export const zInternalHttpapiOAuthErrorResponse = z.object({
  error: z.string().optional(),
  error_description: z.string().optional(),
  pending_token: z.string().optional()
});

export const zInternalHttpapiOAuthTokenResponse = z.object({
  access_token: z.string().optional(),
  expires_in: z.int().optional(),
  refresh_token: z.string().optional(),
  token_type: z.string().optional()
});

export const zInternalHttpapiPatchLibraryRequest = z.object({
  name: z.string().optional(),
  type: z.string().optional()
});

export const zInternalHttpapiPatchProviderSettingsRequest = z.object({
  allowOverrideUserMetadata: z.boolean().optional(),
  metadataApplyMode: z.string().optional(),
  metadataProvider: z.string().optional(),
  metadataWriteTarget: z.string().optional(),
  posterProvider: z.string().optional(),
  subtitleLanguages: z.array(z.string()).optional(),
  subtitleProvider: z.string().optional()
});

export const zInternalHttpapiPlaybackSeriesContext = z.object({
  episode: z.int().optional(),
  librarySlug: z.string().optional(),
  season: z.int().optional(),
  showKey: z.string().optional(),
  showName: z.string().optional()
});

export const zInternalHttpapiProviderAvailability = z.object({
  metadata: z.array(z.string()).optional(),
  poster: z.array(z.string()).optional(),
  subtitle: z.array(z.string()).optional()
});

export const zInternalHttpapiProviderSubtitleTrack = z.object({
  label: z.string().optional(),
  lang: z.string().optional(),
  url: z.string().optional()
});

export const zInternalHttpapiResendInviteRequest = z.object({
  expiresInHours: z.int().optional()
});

export const zInternalHttpapiResetPasswordRequest = z.object({
  password: z.string().optional(),
  token: z.string().optional()
});

export const zInternalHttpapiStatusResponse = z.object({
  status: z.string().optional()
});

export const zInternalHttpapiTrashSettingsResponse = z.object({
  retentionDays: z.int().optional()
});

export const zInternalHttpapiTwoFactorConfirmRequest = z.object({
  code: z.string().optional(),
  pendingToken: z.string().optional()
});

export const zInternalHttpapiTwoFactorSetupRequest = z.object({
  pendingToken: z.string().optional()
});

export const zInternalHttpapiUpdateUserRequest = z.object({
  email: z.string().optional(),
  enabled: z.boolean().optional(),
  role: z.string().optional()
});

export const zInternalHttpapiUserSubtitleTrack = z.object({
  label: z.string().optional(),
  lang: z.string().optional(),
  url: z.string().optional()
});

export const zInternalHttpapiVerifyTwoFactorRequest = z.object({
  code: z.string().optional(),
  pendingToken: z.string().optional()
});

export const zInternalHttpapiWatchPatchRequest = z.object({
  durationSeconds: z.number().optional(),
  positionSeconds: z.number().optional(),
  watched: z.boolean().optional()
});

export const zInternalHttpapiWatchResponse = z.object({
  durationSeconds: z.number().optional(),
  positionSeconds: z.number().optional(),
  watched: z.boolean().optional()
});

export const zSudoStreamInternalAccessLibraryPermissions = z.object({
  create: z.boolean().optional(),
  delete: z.boolean().optional(),
  read: z.boolean().optional(),
  update: z.boolean().optional()
});

export const zSudoStreamInternalAccessGrantInput = z.object({
  libraryId: z.string().optional(),
  permissions: zSudoStreamInternalAccessLibraryPermissions.optional()
});

export const zInternalHttpapiPutGrantsRequest = z.object({
  grants: z.array(zSudoStreamInternalAccessGrantInput).optional()
});

export const zSudoStreamInternalAccessLibraryType = z.enum([
  'film',
  'series',
  'music',
  'photos',
  'other'
]);

export const zSudoStreamInternalAccessLibrary = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  relPath: z.string().optional(),
  roots: z.array(z.string()).optional(),
  slug: z.string().optional(),
  type: zSudoStreamInternalAccessLibraryType.optional()
});

export const zInternalHttpapiLibrariesResponse = z.object({
  libraries: z.array(zSudoStreamInternalAccessLibrary).optional()
});

export const zInternalHttpapiLibraryResponse = z.object({
  library: zSudoStreamInternalAccessLibrary.optional()
});

export const zSudoStreamInternalAccessUserGrantView = z.object({
  library: zSudoStreamInternalAccessLibrary.optional(),
  permissions: zSudoStreamInternalAccessLibraryPermissions.optional()
});

export const zInternalHttpapiGrantsResponse = z.object({
  grants: z.array(zSudoStreamInternalAccessUserGrantView).optional()
});

export const zSudoStreamInternalAuthAdminUser = z.object({
  createdAt: z.string().optional(),
  email: z.string().optional(),
  emailVerified: z.boolean().optional(),
  enabled: z.boolean().optional(),
  has2FA: z.boolean().optional(),
  id: z.string().optional(),
  lastLoginAt: z.string().optional(),
  mustChangePassword: z.boolean().optional(),
  role: z.string().optional(),
  status: z.string().optional()
});

export const zInternalHttpapiAdminUserResponse = z.object({
  user: zSudoStreamInternalAuthAdminUser.optional()
});

export const zInternalHttpapiUsersResponse = z.object({
  users: z.array(zSudoStreamInternalAuthAdminUser).optional()
});

export const zSudoStreamInternalAuthInviteView = z.object({
  createdAt: z.string().optional(),
  email: z.string().optional(),
  expired: z.boolean().optional(),
  expiresAt: z.string().optional(),
  id: z.string().optional(),
  role: z.string().optional()
});

export const zInternalHttpapiInvitesResponse = z.object({
  invites: z.array(zSudoStreamInternalAuthInviteView).optional()
});

export const zSudoStreamInternalAuthPublicUser = z.object({
  email: z.string().optional(),
  has2FA: z.boolean().optional(),
  id: z.string().optional(),
  mustChangePassword: z.boolean().optional(),
  role: z.string().optional()
});

export const zInternalHttpapiAuthTokensResponse = z.object({
  accessToken: z.string().optional(),
  backupCodes: z.array(z.string()).optional(),
  user: zSudoStreamInternalAuthPublicUser.optional()
});

export const zInternalHttpapiLoginResponse = z.object({
  accessToken: z.string().optional(),
  pendingToken: z.string().optional(),
  status: z.string().optional(),
  user: zSudoStreamInternalAuthPublicUser.optional()
});

export const zInternalHttpapiMeResponse = z.object({
  user: zSudoStreamInternalAuthPublicUser.optional()
});

export const zInternalHttpapiRefreshResponse = z.object({
  accessToken: z.string().optional(),
  user: zSudoStreamInternalAuthPublicUser.optional()
});

export const zInternalHttpapiUserResponse = z.object({
  user: zSudoStreamInternalAuthPublicUser.optional()
});

export const zSudoStreamInternalAuthSessionView = z.object({
  createdAt: z.string().optional(),
  current: z.boolean().optional(),
  expiresAt: z.string().optional(),
  id: z.string().optional(),
  ip: z.string().optional(),
  userAgent: z.string().optional()
});

export const zInternalHttpapiSessionsResponse = z.object({
  sessions: z.array(zSudoStreamInternalAuthSessionView).optional()
});

export const zSudoStreamInternalAuthSettings = z.object({
  emailConfirmationRequired: z.boolean().optional(),
  twoFactorRequired: z.boolean().optional()
});

export const zSudoStreamInternalAuthTwoFactorConfirmResult = z.object({
  backupCodes: z.array(z.string()).optional()
});

export const zSudoStreamInternalAuthTwoFactorSetup = z.object({
  otpauthURL: z.string().optional(),
  secret: z.string().optional()
});

export const zSudoStreamInternalCatalogSeasonSummary = z.object({
  episodeCount: z.int().optional(),
  season: z.int().optional()
});

export const zSudoStreamInternalDlnaSettings = z.object({
  enabled: z.boolean().optional(),
  udn: z.string().optional(),
  userId: z.string().optional()
});

export const zSudoStreamInternalHomeshelfLibraryStat = z.object({
  libraryId: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  totalCount: z.int().optional(),
  watchedCount: z.int().optional(),
  watchedPercent: z.number().optional()
});

export const zInternalHttpapiHomeStatsResponse = z.object({
  libraries: z.array(zSudoStreamInternalHomeshelfLibraryStat).optional()
});

export const zSudoStreamInternalHomeshelfShelfItem = z.object({
  durationSeconds: z.number().optional(),
  librarySlug: z.string().optional(),
  path: z.string().optional(),
  positionSeconds: z.number().optional(),
  posterUrl: z.string().optional(),
  title: z.string().optional()
});

export const zInternalHttpapiHomeItemsResponse = z.object({
  items: z.array(zSudoStreamInternalHomeshelfShelfItem).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  total: z.int().optional()
});

export const zSudoStreamInternalMaintenanceRun = z.object({
  action: z.string().optional(),
  finishedAt: z.string().optional(),
  id: z.string().optional(),
  libraryId: z.string().optional(),
  startedAt: z.string().optional(),
  status: z.string().optional(),
  summary: z.record(z.string(), z.unknown()).optional(),
  trigger: z.string().optional()
});

export const zInternalHttpapiMaintenanceRunResponse = z.object({
  run: zSudoStreamInternalMaintenanceRun.optional()
});

export const zInternalHttpapiMaintenanceRunsResponse = z.object({
  runs: z.array(zSudoStreamInternalMaintenanceRun).optional()
});

export const zSudoStreamInternalMaintenanceSchedule = z.object({
  action: z.string().optional(),
  config: z.record(z.string(), z.unknown()).optional(),
  cron: z.string().optional(),
  enabled: z.boolean().optional(),
  id: z.string().optional(),
  libraryId: z.string().optional(),
  updatedAt: z.string().optional()
});

export const zSudoStreamInternalMaintenanceActionStatus = z.object({
  action: z.string().optional(),
  latestRun: zSudoStreamInternalMaintenanceRun.optional(),
  running: z.boolean().optional(),
  schedule: zSudoStreamInternalMaintenanceSchedule.optional()
});

export const zInternalHttpapiMaintenanceStatusResponse = z.object({
  actions: z.array(zSudoStreamInternalMaintenanceActionStatus).optional(),
  cacheBytes: z.int().optional()
});

export const zSudoStreamInternalMaintenanceScheduleInput = z.object({
  action: z.string().optional(),
  config: z.record(z.string(), z.unknown()).optional(),
  cron: z.string().optional(),
  enabled: z.boolean().optional(),
  libraryId: z.string().optional()
});

export const zInternalHttpapiPatchMaintenanceRequest = z.object({
  schedules: z.array(zSudoStreamInternalMaintenanceScheduleInput).optional()
});

export const zSudoStreamInternalMediafsAction = z.object({
  canDelete: z.boolean().optional(),
  download: z.string().optional(),
  play: z.string().optional(),
  thumbnail: z.string().optional()
});

export const zSudoStreamInternalCatalogEpisode = z.object({
  actions: zSudoStreamInternalMediafsAction.optional(),
  episode: z.int().optional(),
  episodeTitle: z.string().optional(),
  favorited: z.boolean().optional(),
  path: z.string().optional(),
  posterUrl: z.string().optional(),
  season: z.int().optional(),
  title: z.string().optional(),
  watched: z.boolean().optional()
});

export const zSudoStreamInternalCatalogMovie = z.object({
  actions: zSudoStreamInternalMediafsAction.optional(),
  favorited: z.boolean().optional(),
  path: z.string().optional(),
  posterUrl: z.string().optional(),
  title: z.string().optional(),
  watched: z.boolean().optional(),
  year: z.int().optional()
});

export const zSudoStreamInternalCatalogSeasonEpisodes = z.object({
  episodes: z.array(zSudoStreamInternalCatalogEpisode).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  season: z.int().optional(),
  total: z.int().optional()
});

export const zSudoStreamInternalCatalogShowDetail = z.object({
  actions: zSudoStreamInternalMediafsAction.optional(),
  episodeCount: z.int().optional(),
  name: z.string().optional(),
  posterPath: z.string().optional(),
  posterUrl: z.string().optional(),
  seasonCount: z.int().optional(),
  seasons: z.array(zSudoStreamInternalCatalogSeasonSummary).optional(),
  showKey: z.string().optional()
});

export const zSudoStreamInternalCatalogShowSummary = z.object({
  actions: zSudoStreamInternalMediafsAction.optional(),
  episodeCount: z.int().optional(),
  name: z.string().optional(),
  posterPath: z.string().optional(),
  posterUrl: z.string().optional(),
  seasonCount: z.int().optional(),
  showKey: z.string().optional()
});

export const zSudoStreamInternalCatalogLibraryCatalog = z.object({
  limit: z.int().optional(),
  movies: z.array(zSudoStreamInternalCatalogMovie).optional(),
  offset: z.int().optional(),
  shows: z.array(zSudoStreamInternalCatalogShowSummary).optional(),
  total: z.int().optional(),
  type: zSudoStreamInternalAccessLibraryType.optional()
});

export const zSudoStreamInternalMediafsBreadcrumb = z.object({
  name: z.string().optional(),
  path: z.string().optional()
});

export const zSudoStreamInternalMediafsItem = z.object({
  actions: zSudoStreamInternalMediafsAction.optional(),
  children: z.array(z.lazy((): any => zSudoStreamInternalMediafsItem)).optional(),
  extension: z.string().optional(),
  favorited: z.boolean().optional(),
  isDir: z.boolean().optional(),
  mimeType: z.string().optional(),
  name: z.string().optional(),
  path: z.string().optional(),
  size: z.int().optional(),
  watched: z.boolean().optional()
});

export const zSudoStreamInternalMediafsBrowseResponse = z.object({
  breadcrumbs: z.array(zSudoStreamInternalMediafsBreadcrumb).optional(),
  folder: zSudoStreamInternalMediafsItem.optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  path: z.string().optional(),
  total: z.int().optional()
});

export const zSudoStreamInternalMetadataFilenameHint = z.object({
  episode: z.int().optional(),
  season: z.int().optional()
});

export const zSudoStreamInternalMetadataPatchTarget = z.enum(['override', 'file']);

export const zSudoStreamInternalMetadataSearchHit = z.object({
  librarySlug: z.string().optional(),
  libraryType: zSudoStreamInternalAccessLibraryType.optional(),
  path: z.string().optional(),
  showKey: z.string().optional(),
  title: z.string().optional()
});

export const zInternalHttpapiSearchResponse = z.object({
  items: z.array(zSudoStreamInternalMetadataSearchHit).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  total: z.int().optional()
});

export const zSudoStreamInternalMetadataVideoFields = z.object({
  actors: z.array(z.string()).optional(),
  audio_channels: z.int().optional(),
  audio_codec: z.string().optional(),
  audio_languages: z.array(z.string()).optional(),
  bitrate: z.int().optional(),
  composer: z.string().optional(),
  content_rating: z.string().optional(),
  country: z.string().optional(),
  description: z.string().optional(),
  directors: z.array(z.string()).optional(),
  duration_seconds: z.number().optional(),
  ed2k_hash: z.string().optional(),
  episode: z.int().optional(),
  episode_title: z.string().optional(),
  frame_rate: z.string().optional(),
  genres: z.array(z.string()).optional(),
  hash_file_size: z.int().optional(),
  height: z.int().optional(),
  imdb_id: z.string().optional(),
  language: z.string().optional(),
  movie_hash: z.string().optional(),
  original_title: z.string().optional(),
  producers: z.array(z.string()).optional(),
  release_date: z.string().optional(),
  season: z.int().optional(),
  show: z.string().optional(),
  sort_title: z.string().optional(),
  studio: z.string().optional(),
  tags: z.array(z.string()).optional(),
  title: z.string().optional(),
  tmdb_id: z.string().optional(),
  tvdb_id: z.string().optional(),
  tvmaze_id: z.string().optional(),
  video_codec: z.string().optional(),
  width: z.int().optional(),
  writers: z.array(z.string()).optional(),
  year: z.int().optional()
});

export const zSudoStreamInternalMetadataSourceFields = z.object({
  original: zSudoStreamInternalMetadataVideoFields.optional(),
  override: zSudoStreamInternalMetadataVideoFields.optional()
});

export const zSudoStreamInternalMetadataMetadataResponse = z.object({
  display_name: z.string().optional(),
  effective: zSudoStreamInternalMetadataVideoFields.optional(),
  filename_hint: zSudoStreamInternalMetadataFilenameHint.optional(),
  library_type: zSudoStreamInternalAccessLibraryType.optional(),
  overridden_by: z.string().optional(),
  path: z.string().optional(),
  probed_at: z.string().optional(),
  source: zSudoStreamInternalMetadataSourceFields.optional(),
  uses_metadata_for_display: z.boolean().optional()
});

export const zSudoStreamInternalMetadataJsonValue = z.record(z.string(), z.unknown());

export const zSudoStreamInternalMetadataPatchRequest = z.object({
  fields: z.record(z.string(), zSudoStreamInternalMetadataJsonValue).optional(),
  target: zSudoStreamInternalMetadataPatchTarget.optional()
});

export const zSudoStreamInternalNetworkProbeResult = z.object({
  durationMs: z.int().optional(),
  error: z.string().optional(),
  ok: z.boolean().optional(),
  statusCode: z.int().optional(),
  via: z.string().optional()
});

export const zSudoStreamInternalNetworkSettings = z.object({
  hasProxyPassword: z.boolean().optional(),
  noProxy: z.string().optional(),
  proxyPassword: z.string().optional(),
  proxyUrl: z.string().optional(),
  proxyUser: z.string().optional()
});

export const zSudoStreamInternalPlaybackDirectPlayProfile = z.object({
  audioCodec: z.string().optional(),
  container: z.string().optional(),
  videoCodec: z.string().optional()
});

export const zSudoStreamInternalPlaybackDeviceProfile = z.object({
  directPlay: z.array(zSudoStreamInternalPlaybackDirectPlayProfile).optional(),
  maxStaticBitrate: z.int().optional(),
  preferHls: z.boolean().optional(),
  subtitle: z.array(z.string()).optional()
});

export const zInternalHttpapiPlaybackNegotiateRequest = z.object({
  deviceProfile: zSudoStreamInternalPlaybackDeviceProfile.optional(),
  fallback: z.boolean().optional(),
  qualityHeight: z.int().optional(),
  transcode: z.boolean().optional()
});

export const zSudoStreamInternalPlaybackPlayMethod = z.enum([
  'directPlay',
  'remux',
  'transcode'
]);

export const zSudoStreamInternalProviderSettings = z.object({
  allowOverrideUserMetadata: z.boolean().optional(),
  libraryId: z.string().optional(),
  metadataApplyMode: z.string().optional(),
  metadataProvider: z.string().optional(),
  metadataWriteTarget: z.string().optional(),
  posterProvider: z.string().optional(),
  subtitleLanguages: z.array(z.string()).optional(),
  subtitleProvider: z.string().optional(),
  updatedAt: z.string().optional()
});

export const zInternalHttpapiProviderSettingsResponse = z.object({
  available: zInternalHttpapiProviderAvailability.optional(),
  settings: zSudoStreamInternalProviderSettings.optional()
});

export const zSudoStreamInternalSkipsegmentIntro = z.object({
  endMs: z.int().optional(),
  source: z.string().optional(),
  startMs: z.int().optional()
});

export const zSudoStreamInternalTranscodeChapterInfo = z.object({
  endSeconds: z.number().optional(),
  startSeconds: z.number().optional(),
  title: z.string().optional()
});

export const zSudoStreamInternalTranscodeDownmixAlgorithm = z.enum(['none', 'ac4']);

export const zSudoStreamInternalTranscodeHwAccel = z.enum([
  'off',
  'qsv',
  'vaapi',
  'nvenc',
  'rockchip'
]);

export const zSudoStreamInternalTranscodePackagingMode = z.enum(['remux', 'transcode']);

export const zSudoStreamInternalTranscodeQualityInfo = z.object({
  height: z.int().optional(),
  label: z.string().optional()
});

export const zSudoStreamInternalTranscodeStatus = z.enum([
  'idle',
  'ready',
  'processing',
  'error'
]);

export const zSudoStreamInternalTranscodeToneMappingAlgorithm = z.enum([
  'bt2390',
  'hable',
  'reinhard',
  'mobius'
]);

export const zSudoStreamInternalTranscodeTrackInfo = z.object({
  id: z.string().optional(),
  label: z.string().optional()
});

export const zInternalHttpapiPlaybackResponse = z.object({
  audioTracks: z.array(zSudoStreamInternalTranscodeTrackInfo).optional(),
  chapters: z.array(zSudoStreamInternalTranscodeChapterInfo).optional(),
  durationSeconds: z.number().optional(),
  encoder: z.string().optional(),
  error: z.string().optional(),
  masterUrl: z.string().optional(),
  packagingMode: zSudoStreamInternalTranscodePackagingMode.optional(),
  playMethod: zSudoStreamInternalPlaybackPlayMethod.optional(),
  providerSubtitleTracks: z.array(zInternalHttpapiProviderSubtitleTrack).optional(),
  qualities: z.array(zSudoStreamInternalTranscodeQualityInfo).optional(),
  series: zInternalHttpapiPlaybackSeriesContext.optional(),
  skipIntro: zSudoStreamInternalSkipsegmentIntro.optional(),
  status: zSudoStreamInternalTranscodeStatus.optional(),
  streamUrl: z.string().optional(),
  subtitleTracks: z.array(zSudoStreamInternalTranscodeTrackInfo).optional(),
  toneMapped: z.boolean().optional(),
  userSubtitle: zInternalHttpapiUserSubtitleTrack.optional()
});

export const zSudoStreamInternalTranscodeTranscodeSettings = z.object({
  downmixAlgorithm: zSudoStreamInternalTranscodeDownmixAlgorithm.optional(),
  hwAccel: zSudoStreamInternalTranscodeHwAccel.optional(),
  toneMappingAlgorithm: zSudoStreamInternalTranscodeToneMappingAlgorithm.optional(),
  toneMappingEnabled: z.boolean().optional()
});

export const zSudoStreamInternalTrashItem = z.object({
  deletedAt: z.string().optional(),
  deletedBy: z.string().optional(),
  id: z.string().optional(),
  libraryId: z.string().optional(),
  originalRelPath: z.string().optional(),
  trashRelPath: z.string().optional()
});

export const zInternalHttpapiTrashListResponse = z.object({
  items: z.array(zSudoStreamInternalTrashItem).optional()
});

/**
 * OK
 */
export const zGetApiAdminDlnaSettingsResponse = zSudoStreamInternalDlnaSettings;

/**
 * DLNA settings
 */
export const zPatchApiAdminDlnaSettingsBody = zSudoStreamInternalDlnaSettings;

/**
 * OK
 */
export const zPatchApiAdminDlnaSettingsResponse = zSudoStreamInternalDlnaSettings;

export const zGetApiAdminFolderTreeQuery = z.object({
  path: z.string().optional()
});

/**
 * OK
 */
export const zGetApiAdminFolderTreeResponse = zInternalHttpapiFolderTreeResponse;

export const zGetApiAdminInvitesQuery = z.object({
  email: z.string().optional()
});

/**
 * OK
 */
export const zGetApiAdminInvitesResponse = zInternalHttpapiInvitesResponse;

/**
 * Invite
 */
export const zPostApiAdminInvitesBody = zInternalHttpapiCreateInviteRequest;

/**
 * No Content
 */
export const zPostApiAdminInvitesResponse = z.void();

export const zDeleteApiAdminInvitesByIdPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zDeleteApiAdminInvitesByIdResponse = z.void();

/**
 * Optional TTL override
 */
export const zPostApiAdminInvitesByIdResendBody = zInternalHttpapiResendInviteRequest;

export const zPostApiAdminInvitesByIdResendPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zPostApiAdminInvitesByIdResendResponse = z.void();

/**
 * OK
 */
export const zGetApiAdminLibrariesResponse = zInternalHttpapiLibrariesResponse;

/**
 * Library fields
 */
export const zPostApiAdminLibrariesBody = zInternalHttpapiCreateLibraryRequest;

/**
 * Created
 */
export const zPostApiAdminLibrariesResponse = zInternalHttpapiLibraryResponse;

/**
 * OK
 */
export const zPostApiAdminLibrariesSyncResponse = zInternalHttpapiLibrariesResponse;

export const zDeleteApiAdminLibrariesByIdPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zDeleteApiAdminLibrariesByIdResponse = z.void();

/**
 * Library fields
 */
export const zPatchApiAdminLibrariesByIdBody = zInternalHttpapiPatchLibraryRequest;

export const zPatchApiAdminLibrariesByIdPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPatchApiAdminLibrariesByIdResponse = zInternalHttpapiLibraryResponse;

export const zGetApiAdminLibrariesByIdMaintenancePath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zGetApiAdminLibrariesByIdMaintenanceResponse = zInternalHttpapiMaintenanceStatusResponse;

/**
 * Schedules
 */
export const zPatchApiAdminLibrariesByIdMaintenanceBody = zInternalHttpapiPatchMaintenanceRequest;

export const zPatchApiAdminLibrariesByIdMaintenancePath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPatchApiAdminLibrariesByIdMaintenanceResponse = zInternalHttpapiMaintenanceStatusResponse;

export const zGetApiAdminLibrariesByIdProvidersPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zGetApiAdminLibrariesByIdProvidersResponse = zInternalHttpapiProviderSettingsResponse;

/**
 * Provider settings
 */
export const zPatchApiAdminLibrariesByIdProvidersBody = zInternalHttpapiPatchProviderSettingsRequest;

export const zPatchApiAdminLibrariesByIdProvidersPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPatchApiAdminLibrariesByIdProvidersResponse = zInternalHttpapiProviderSettingsResponse;

export const zDeleteApiAdminLibrariesByIdRootsPath = z.object({
  id: z.string()
});

export const zDeleteApiAdminLibrariesByIdRootsQuery = z.object({
  path: z.string()
});

export const zDeleteApiAdminLibrariesByIdRootsResponse = z.union([
  zInternalHttpapiLibraryResponse,
  z.void()
]);

/**
 * Folder
 */
export const zPostApiAdminLibrariesByIdRootsBody = zInternalHttpapiAddLibraryRootRequest;

export const zPostApiAdminLibrariesByIdRootsPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPostApiAdminLibrariesByIdRootsResponse = zInternalHttpapiLibraryResponse;

export const zPostApiAdminLibrariesByIdSyncPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPostApiAdminLibrariesByIdSyncResponse = zInternalHttpapiLibraryResponse;

/**
 * OK
 */
export const zGetApiAdminMaintenanceResponse = zInternalHttpapiMaintenanceStatusResponse;

/**
 * Schedules
 */
export const zPatchApiAdminMaintenanceBody = zInternalHttpapiPatchMaintenanceRequest;

/**
 * OK
 */
export const zPatchApiAdminMaintenanceResponse = zInternalHttpapiMaintenanceStatusResponse;

export const zGetApiAdminMaintenanceRunsQuery = z.object({
  limit: z.int().optional()
});

/**
 * OK
 */
export const zGetApiAdminMaintenanceRunsResponse = zInternalHttpapiMaintenanceRunsResponse;

export const zPostApiAdminMaintenanceByActionRunPath = z.object({
  action: z.string()
});

export const zPostApiAdminMaintenanceByActionRunQuery = z.object({
  libraryId: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAdminMaintenanceByActionRunResponse = zInternalHttpapiMaintenanceRunResponse;

/**
 * OK
 */
export const zGetApiAdminNetworkSettingsResponse = zSudoStreamInternalNetworkSettings;

/**
 * Network settings
 */
export const zPatchApiAdminNetworkSettingsBody = zSudoStreamInternalNetworkSettings;

/**
 * OK
 */
export const zPatchApiAdminNetworkSettingsResponse = zSudoStreamInternalNetworkSettings;

/**
 * Draft network settings
 */
export const zPostApiAdminNetworkSettingsTestBody = zSudoStreamInternalNetworkSettings;

/**
 * OK
 */
export const zPostApiAdminNetworkSettingsTestResponse = zSudoStreamInternalNetworkProbeResult;

export const zDeleteApiAdminSessionsByIdPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zDeleteApiAdminSessionsByIdResponse = z.void();

/**
 * OK
 */
export const zGetApiAdminSettingsResponse = zSudoStreamInternalAuthSettings;

/**
 * Settings
 */
export const zPatchApiAdminSettingsBody = zSudoStreamInternalAuthSettings;

/**
 * OK
 */
export const zPatchApiAdminSettingsResponse = zSudoStreamInternalAuthSettings;

/**
 * OK
 */
export const zGetApiAdminTranscodeSettingsResponse = zSudoStreamInternalTranscodeTranscodeSettings;

/**
 * Transcode settings
 */
export const zPatchApiAdminTranscodeSettingsBody = zSudoStreamInternalTranscodeTranscodeSettings;

/**
 * OK
 */
export const zPatchApiAdminTranscodeSettingsResponse = zSudoStreamInternalTranscodeTranscodeSettings;

/**
 * No Content
 */
export const zDeleteApiAdminTrashResponse = z.void();

/**
 * OK
 */
export const zGetApiAdminTrashResponse = zInternalHttpapiTrashListResponse;

/**
 * OK
 */
export const zGetApiAdminTrashSettingsResponse = zInternalHttpapiTrashSettingsResponse;

/**
 * Recycle bin settings
 */
export const zPatchApiAdminTrashSettingsBody = zInternalHttpapiTrashSettingsResponse;

/**
 * OK
 */
export const zPatchApiAdminTrashSettingsResponse = zInternalHttpapiTrashSettingsResponse;

export const zDeleteApiAdminTrashByIdPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zDeleteApiAdminTrashByIdResponse = z.void();

export const zPostApiAdminTrashByIdRestorePath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPostApiAdminTrashByIdRestoreResponse = zSudoStreamInternalTrashItem;

/**
 * OK
 */
export const zGetApiAdminUsersResponse = zInternalHttpapiUsersResponse;

/**
 * New user
 */
export const zPostApiAdminUsersBody = zInternalHttpapiCreateUserRequest;

/**
 * Created
 */
export const zPostApiAdminUsersResponse = zInternalHttpapiUserResponse;

export const zDeleteApiAdminUsersByIdPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zDeleteApiAdminUsersByIdResponse = z.void();

/**
 * User patch
 */
export const zPatchApiAdminUsersByIdBody = zInternalHttpapiUpdateUserRequest;

export const zPatchApiAdminUsersByIdPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPatchApiAdminUsersByIdResponse = zInternalHttpapiAdminUserResponse;

export const zPostApiAdminUsersById2FaResetPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zPostApiAdminUsersById2FaResetResponse = z.void();

export const zGetApiAdminUsersByIdLibrariesPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zGetApiAdminUsersByIdLibrariesResponse = zInternalHttpapiGrantsResponse;

/**
 * Grant list
 */
export const zPutApiAdminUsersByIdLibrariesBody = zInternalHttpapiPutGrantsRequest;

export const zPutApiAdminUsersByIdLibrariesPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zPutApiAdminUsersByIdLibrariesResponse = zInternalHttpapiGrantsResponse;

export const zPostApiAdminUsersByIdResendConfirmPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zPostApiAdminUsersByIdResendConfirmResponse = z.void();

export const zGetApiAdminUsersByIdSessionsPath = z.object({
  id: z.string()
});

/**
 * OK
 */
export const zGetApiAdminUsersByIdSessionsResponse = zInternalHttpapiSessionsResponse;

export const zPostApiAdminUsersByIdSessionsRevokeAllPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zPostApiAdminUsersByIdSessionsRevokeAllResponse = z.void();

/**
 * Password and TOTP code
 */
export const zDeleteApiAuth2FaBody = zInternalHttpapiDisableTwoFactorRequest;

/**
 * No Content
 */
export const zDeleteApiAuth2FaResponse = z.void();

/**
 * TOTP code
 */
export const zPostApiAuth2FaConfirmBody = zInternalHttpapiTwoFactorConfirmRequest;

/**
 * OK
 */
export const zPostApiAuth2FaConfirmResponse = zSudoStreamInternalAuthTwoFactorConfirmResult;

/**
 * Optional pending token
 */
export const zPostApiAuth2FaSetupBody = zInternalHttpapiTwoFactorSetupRequest;

/**
 * OK
 */
export const zPostApiAuth2FaSetupResponse = zSudoStreamInternalAuthTwoFactorSetup;

/**
 * Pending token and code
 */
export const zPostApiAuth2FaVerifyBody = zInternalHttpapiVerifyTwoFactorRequest;

/**
 * OK
 */
export const zPostApiAuth2FaVerifyResponse = zInternalHttpapiAuthTokensResponse;

/**
 * Invite token
 */
export const zPostApiAuthAcceptInviteBody = zInternalHttpapiAcceptInviteRequest;

/**
 * No Content
 */
export const zPostApiAuthAcceptInviteResponse = z.void();

/**
 * Email change
 */
export const zPostApiAuthChangeEmailBody = zInternalHttpapiChangeEmailRequest;

/**
 * No Content
 */
export const zPostApiAuthChangeEmailResponse = z.void();

/**
 * Password change
 */
export const zPostApiAuthChangePasswordBody = zInternalHttpapiChangePasswordRequest;

/**
 * OK
 */
export const zPostApiAuthChangePasswordResponse = zInternalHttpapiLoginResponse;

export const zGetApiAuthConfirmEmailQuery = z.object({
  token: z.string()
});

/**
 * OK
 */
export const zGetApiAuthConfirmEmailResponse = zInternalHttpapiStatusResponse;

/**
 * Email
 */
export const zPostApiAuthForgotPasswordBody = zInternalHttpapiForgotPasswordRequest;

/**
 * No Content
 */
export const zPostApiAuthForgotPasswordResponse = z.void();

/**
 * Credentials
 */
export const zPostApiAuthLoginBody = zInternalHttpapiLoginRequest;

/**
 * OK
 */
export const zPostApiAuthLoginResponse = zInternalHttpapiLoginResponse;

/**
 * No Content
 */
export const zPostApiAuthLogoutResponse = z.void();

/**
 * OK
 */
export const zGetApiAuthMeResponse = zInternalHttpapiMeResponse;

/**
 * OK
 */
export const zPostApiAuthRefreshResponse = zInternalHttpapiRefreshResponse;

/**
 * Reset token
 */
export const zPostApiAuthResetPasswordBody = zInternalHttpapiResetPasswordRequest;

/**
 * No Content
 */
export const zPostApiAuthResetPasswordResponse = z.void();

/**
 * OK
 */
export const zGetApiAuthSessionsResponse = zInternalHttpapiSessionsResponse;

/**
 * No Content
 */
export const zPostApiAuthSessionsRevokeAllResponse = z.void();

export const zDeleteApiAuthSessionsByIdPath = z.object({
  id: z.string()
});

/**
 * No Content
 */
export const zDeleteApiAuthSessionsByIdResponse = z.void();

export const zGetApiBrowseQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiBrowseResponse = zSudoStreamInternalMediafsBrowseResponse;

export const zGetApiBrowseByPathPath = z.object({
  path: z.string()
});

export const zGetApiBrowseByPathQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiBrowseByPathResponse = zSudoStreamInternalMediafsBrowseResponse;

export const zGetApiCatalogByLibrarySlugPath = z.object({
  librarySlug: z.string()
});

export const zGetApiCatalogByLibrarySlugQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiCatalogByLibrarySlugResponse = zSudoStreamInternalCatalogLibraryCatalog;

export const zGetApiCatalogByLibrarySlugShowsByShowKeyPath = z.object({
  librarySlug: z.string(),
  showKey: z.string()
});

/**
 * OK
 */
export const zGetApiCatalogByLibrarySlugShowsByShowKeyResponse = zSudoStreamInternalCatalogShowDetail;

export const zGetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesPath = z.object({
  librarySlug: z.string(),
  showKey: z.string(),
  season: z.int()
});

export const zGetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiCatalogByLibrarySlugShowsByShowKeySeasonsBySeasonEpisodesResponse = zSudoStreamInternalCatalogSeasonEpisodes;

export const zGetApiDownloadByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiDownloadByPathResponse = z.string();

export const zGetApiFavoriteByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiFavoriteByPathResponse = zInternalHttpapiFavoriteResponse;

/**
 * Favorite flag
 */
export const zPatchApiFavoriteByPathBody = zInternalHttpapiFavoritePatchRequest;

export const zPatchApiFavoriteByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zPatchApiFavoriteByPathResponse = zInternalHttpapiFavoriteResponse;

/**
 * OK
 */
export const zGetApiHealthResponse = zInternalHttpapiHealthResponse;

/**
 * OK
 */
export const zGetApiLibrariesResponse = zInternalHttpapiLibrariesResponse;

export const zGetApiMeContinueQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiMeContinueResponse = zInternalHttpapiHomeItemsResponse;

export const zGetApiMeFavoritesQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiMeFavoritesResponse = zInternalHttpapiHomeItemsResponse;

/**
 * OK
 */
export const zGetApiMeStatsResponse = zInternalHttpapiHomeStatsResponse;

export const zGetApiMeUnwatchedQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiMeUnwatchedResponse = zInternalHttpapiHomeItemsResponse;

export const zGetApiMeWatchedQuery = z.object({
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiMeWatchedResponse = zInternalHttpapiHomeItemsResponse;

export const zDeleteApiMediaByPathPath = z.object({
  path: z.string()
});

export const zDeleteApiMediaByPathQuery = z.object({
  recursive: z.boolean().optional()
});

/**
 * No Content
 */
export const zDeleteApiMediaByPathResponse = z.void();

export const zGetApiMetadataByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiMetadataByPathResponse = zSudoStreamInternalMetadataMetadataResponse;

/**
 * Metadata patch
 */
export const zPatchApiMetadataByPathBody = zSudoStreamInternalMetadataPatchRequest;

export const zPatchApiMetadataByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zPatchApiMetadataByPathResponse = zSudoStreamInternalMetadataMetadataResponse;

export const zPostApiOauthTokenBody = z.record(z.string(), z.unknown());

/**
 * OK
 */
export const zPostApiOauthTokenResponse = zInternalHttpapiOAuthTokenResponse;

export const zGetApiPlayByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiPlayByPathResponse = z.string();

export const zGetApiPlaybackByPathPath = z.object({
  path: z.string()
});

export const zGetApiPlaybackByPathQuery = z.object({
  transcode: z.boolean().optional(),
  fallback: z.boolean().optional()
});

/**
 * OK
 */
export const zGetApiPlaybackByPathResponse = zInternalHttpapiPlaybackResponse;

/**
 * Device profile and quality selection
 */
export const zPostApiPlaybackByPathBody = zInternalHttpapiPlaybackNegotiateRequest;

export const zPostApiPlaybackByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zPostApiPlaybackByPathResponse = zInternalHttpapiPlaybackResponse;

export const zGetApiProviderPosterByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiProviderPosterByPathResponse = z.string();

export const zGetApiProviderSubtitleByPathPath = z.object({
  path: z.string()
});

export const zGetApiProviderSubtitleByPathQuery = z.object({
  lang: z.string()
});

/**
 * OK
 */
export const zGetApiProviderSubtitleByPathResponse = z.string();

export const zGetApiSearchQuery = z.object({
  q: z.string(),
  limit: z.int().optional(),
  offset: z.int().optional()
});

/**
 * OK
 */
export const zGetApiSearchResponse = zInternalHttpapiSearchResponse;

export const zGetApiStreamByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiStreamByPathResponse = z.string();

export const zGetApiThumbnailByPathPath = z.object({
  path: z.string()
});

export const zGetApiThumbnailByPathQuery = z.object({
  w: z.int().gte(32).lte(1024).optional().default(320),
  h: z.int().gte(32).lte(1024).optional().default(320)
});

/**
 * OK
 */
export const zGetApiThumbnailByPathResponse = z.string();

export const zDeleteApiUserSubtitleByPathPath = z.object({
  path: z.string()
});

/**
 * No Content
 */
export const zDeleteApiUserSubtitleByPathResponse = z.void();

export const zGetApiUserSubtitleByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiUserSubtitleByPathResponse = z.string();

/**
 * ISO 639-1 language code
 */
export const zPutApiUserSubtitleByPathBody = z.object({
  file: z.string(),
  label: z.string().optional(),
  lang: z.string().optional()
});

export const zPutApiUserSubtitleByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zPutApiUserSubtitleByPathResponse = zInternalHttpapiUserSubtitleTrack;

export const zGetApiWatchByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zGetApiWatchByPathResponse = zInternalHttpapiWatchResponse;

/**
 * Watched flag and optional progress
 */
export const zPatchApiWatchByPathBody = zInternalHttpapiWatchPatchRequest;

export const zPatchApiWatchByPathPath = z.object({
  path: z.string()
});

/**
 * OK
 */
export const zPatchApiWatchByPathResponse = zInternalHttpapiWatchResponse;

/**
 * OK
 */
export const zGetMetricsResponse = z.string();
